export const LOCAL_STORAGE: any = {
    ZEPHYR_TESTCASE_FILTERS: 'ZEPHYR_TESTCASE_FILTERS',
    ZEPHYR_REQUIREMENT_FILTERS: 'ZEPHYR_REQUIREMENT_FILTERS',
    ZEPHYR_TEST_SCHEDULE_FILTERS: 'ZEPHYR_TEST_SCHEDULE_FILTERS',
    ZEPHYR_DASHBORAD_LIST: 'ZEPHYR_DASHBORAD_LIST'
};
