/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../../../app/view/components/defects/defect_tracking/search/bulkEdit/defect_bulk_edit.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '../../../../../../../../app/actions/defects.action';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/constants';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/http/src/http';
import * as import11 from '../../../../../../../../app/view/components/common/modal/modal.component';
import * as import12 from '../../../../common/modal/modal.component.ngfactory';
import * as import13 from '../../../../../../../../app/view/components/common/select/select.component';
import * as import14 from '../../../../common/select/select.component.ngfactory';
import * as import15 from '@angular/core/src/linker/element_ref';
export class Wrapper_DefectBulkEditComponent {
  /*private*/ _eventHandler:Function;
  context:import0.DefectBulkEditComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  subscription0:any;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.DefectBulkEditComponent(p0);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_selectedDefects(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.selectedDefects = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.onDefectBulkUpdate.subscribe(_eventHandler.bind(view,'onDefectBulkUpdate'))); }
  }
}
var renderType_DefectBulkEditComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_DefectBulkEditComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.DefectBulkEditComponent>;
  _DefectsAction_0_3:import6.DefectsAction;
  _DefectBulkEditComponent_0_4:Wrapper_DefectBulkEditComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DefectBulkEditComponent_Host0,renderType_DefectBulkEditComponent_Host,import7.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'zee-defect-bulk-edit',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_DefectBulkEditComponent0(this.viewUtils,this,0,this._el_0);
    this._DefectsAction_0_3 = new import6.DefectsAction(this.injectorGet(import10.Http,this.parentIndex));
    this._DefectBulkEditComponent_0_4 = new Wrapper_DefectBulkEditComponent(this._DefectsAction_0_3);
    this.compView_0.create(this._DefectBulkEditComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._DefectBulkEditComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import6.DefectsAction) && (0 === requestNodeIndex))) { return this._DefectsAction_0_3; }
    if (((token === import0.DefectBulkEditComponent) && (0 === requestNodeIndex))) { return this._DefectBulkEditComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefectBulkEditComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._DefectBulkEditComponent_0_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._DefectBulkEditComponent_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const DefectBulkEditComponentNgFactory:import9.ComponentFactory<import0.DefectBulkEditComponent> = new import9.ComponentFactory<import0.DefectBulkEditComponent>('zee-defect-bulk-edit',View_DefectBulkEditComponent_Host0,import0.DefectBulkEditComponent);
const styles_DefectBulkEditComponent:any[] = ([] as any[]);
var renderType_DefectBulkEditComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_DefectBulkEditComponent,{});
export class View_DefectBulkEditComponent0 extends import2.AppView<import0.DefectBulkEditComponent> {
  _el_0:any;
  compView_0:import2.AppView<import11.ModalComponent>;
  _ModalComponent_0_3:import12.Wrapper_ModalComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  compView_20:import2.AppView<import13.SelectComponent>;
  _SelectComponent_20_3:import14.Wrapper_SelectComponent;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  compView_31:import2.AppView<import13.SelectComponent>;
  _SelectComponent_31_3:import14.Wrapper_SelectComponent;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  compView_42:import2.AppView<import13.SelectComponent>;
  _SelectComponent_42_3:import14.Wrapper_SelectComponent;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  compView_53:import2.AppView<import13.SelectComponent>;
  _SelectComponent_53_3:import14.Wrapper_SelectComponent;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  compView_64:import2.AppView<import13.SelectComponent>;
  _SelectComponent_64_3:import14.Wrapper_SelectComponent;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _el_75:any;
  compView_75:import2.AppView<import13.SelectComponent>;
  _SelectComponent_75_3:import14.Wrapper_SelectComponent;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  compView_86:import2.AppView<import13.SelectComponent>;
  _SelectComponent_86_3:import14.Wrapper_SelectComponent;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DefectBulkEditComponent0,renderType_DefectBulkEditComponent,import7.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'zui-modal',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import12.View_ModalComponent0(this.viewUtils,this,0,this._el_0);
    this._ModalComponent_0_3 = new import12.Wrapper_ModalComponent(new import15.ElementRef(this._el_0),this.compView_0.ref);
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'zui-modal-body',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','defect-bulk-edit-header'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_6,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Values to change',(null as any));
    this._text_9 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_10 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','defect-bulk-edit-wrapper'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'span',new import3.InlineArray2(2,'class','col-md-4 label'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Component',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_13,'span',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'zee-select',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_20 = new import14.View_SelectComponent0(this.viewUtils,this,20,this._el_20);
    this._SelectComponent_20_3 = new import14.Wrapper_SelectComponent(new import15.ElementRef(this._el_20));
    this.compView_20.create(this._SelectComponent_20_3.context);
    this._text_21 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_11,'\n\n            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'span',new import3.InlineArray2(2,'class','col-md-4 label'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Status',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_24,'span',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n                    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'zee-select',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_31 = new import14.View_SelectComponent0(this.viewUtils,this,31,this._el_31);
    this._SelectComponent_31_3 = new import14.Wrapper_SelectComponent(new import15.ElementRef(this._el_31));
    this.compView_31.create(this._SelectComponent_31_3.context);
    this._text_32 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._text_33 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_34 = this.renderer.createText(this._el_11,'\n\n            ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'span',new import3.InlineArray2(2,'class','col-md-4 label'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Resolution',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_35,'span',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'zee-select',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_42 = new import14.View_SelectComponent0(this.viewUtils,this,42,this._el_42);
    this._SelectComponent_42_3 = new import14.Wrapper_SelectComponent(new import15.ElementRef(this._el_42));
    this.compView_42.create(this._SelectComponent_42_3.context);
    this._text_43 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._text_44 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._text_45 = this.renderer.createText(this._el_11,'\n\n            ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n                ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'span',new import3.InlineArray2(2,'class','col-md-4 label'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Version',(null as any));
    this._text_50 = this.renderer.createText(this._el_46,'\n                ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_46,'span',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n                    ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_51,'zee-select',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_53 = new import14.View_SelectComponent0(this.viewUtils,this,53,this._el_53);
    this._SelectComponent_53_3 = new import14.Wrapper_SelectComponent(new import15.ElementRef(this._el_53));
    this.compView_53.create(this._SelectComponent_53_3.context);
    this._text_54 = this.renderer.createText(this._el_51,'\n                ',(null as any));
    this._text_55 = this.renderer.createText(this._el_46,'\n            ',(null as any));
    this._text_56 = this.renderer.createText(this._el_11,'\n\n            ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'\n                ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_57,'span',new import3.InlineArray2(2,'class','col-md-4 label'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'FixVersion',(null as any));
    this._text_61 = this.renderer.createText(this._el_57,'\n                ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_57,'span',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'\n                    ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_62,'zee-select',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_64 = new import14.View_SelectComponent0(this.viewUtils,this,64,this._el_64);
    this._SelectComponent_64_3 = new import14.Wrapper_SelectComponent(new import15.ElementRef(this._el_64));
    this.compView_64.create(this._SelectComponent_64_3.context);
    this._text_65 = this.renderer.createText(this._el_62,'\n                ',(null as any));
    this._text_66 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._text_67 = this.renderer.createText(this._el_11,'\n\n            ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'\n                ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_68,'span',new import3.InlineArray2(2,'class','col-md-4 label'),(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'Priority',(null as any));
    this._text_72 = this.renderer.createText(this._el_68,'\n                ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_68,'span',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'\n                    ',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_73,'zee-select',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_75 = new import14.View_SelectComponent0(this.viewUtils,this,75,this._el_75);
    this._SelectComponent_75_3 = new import14.Wrapper_SelectComponent(new import15.ElementRef(this._el_75));
    this.compView_75.create(this._SelectComponent_75_3.context);
    this._text_76 = this.renderer.createText(this._el_73,'\n                ',(null as any));
    this._text_77 = this.renderer.createText(this._el_68,'\n            ',(null as any));
    this._text_78 = this.renderer.createText(this._el_11,'\n\n            ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'\n                ',(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_79,'span',new import3.InlineArray2(2,'class','col-md-4 label'),(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'Assignee',(null as any));
    this._text_83 = this.renderer.createText(this._el_79,'\n                ',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_79,'span',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'\n                    ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_84,'zee-select',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_86 = new import14.View_SelectComponent0(this.viewUtils,this,86,this._el_86);
    this._SelectComponent_86_3 = new import14.Wrapper_SelectComponent(new import15.ElementRef(this._el_86));
    this.compView_86.create(this._SelectComponent_86_3.context);
    this._text_87 = this.renderer.createText(this._el_84,'\n                ',(null as any));
    this._text_88 = this.renderer.createText(this._el_79,'\n            ',(null as any));
    this._text_89 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_90 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_91 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,(null as any),'zui-modal-footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'\n        ',(null as any));
    this._el_94 = import3.createRenderElement(this.renderer,this._el_92,'button',new import3.InlineArray8(6,'class','zui-btn zui-btn-sec','data-dismiss','modal','type','button'),(null as any));
    this._text_95 = this.renderer.createText(this._el_94,'Cancel',(null as any));
    this._text_96 = this.renderer.createText(this._el_92,'\n        ',(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_92,'button',new import3.InlineArray4(4,'class','zui-btn zui-btn-primary','type','button'),(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'Save',(null as any));
    this._text_99 = this.renderer.createText(this._el_92,'\n    ',(null as any));
    this._text_100 = this.renderer.createText((null as any),'\n',(null as any));
    this.compView_0.create(this._ModalComponent_0_3.context);
    this._text_101 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'onClose',(null as any)),this.eventHandler(this.handleEvent_0));
    this._ModalComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true,false,false,false);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray4(4,'onSelect',(null as any),'onUnselect',(null as any)),this.eventHandler(this.handleEvent_20));
    this._SelectComponent_20_3.subscribe(this,this.eventHandler(this.handleEvent_20),true,true,false,false);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_31,new import3.InlineArray4(4,'onSelect',(null as any),'onUnselect',(null as any)),this.eventHandler(this.handleEvent_31));
    this._SelectComponent_31_3.subscribe(this,this.eventHandler(this.handleEvent_31),true,true,false,false);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_42,new import3.InlineArray4(4,'onSelect',(null as any),'onUnselect',(null as any)),this.eventHandler(this.handleEvent_42));
    this._SelectComponent_42_3.subscribe(this,this.eventHandler(this.handleEvent_42),true,true,false,false);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_53,new import3.InlineArray4(4,'onSelect',(null as any),'onUnselect',(null as any)),this.eventHandler(this.handleEvent_53));
    this._SelectComponent_53_3.subscribe(this,this.eventHandler(this.handleEvent_53),true,true,false,false);
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_64,new import3.InlineArray4(4,'onSelect',(null as any),'onUnselect',(null as any)),this.eventHandler(this.handleEvent_64));
    this._SelectComponent_64_3.subscribe(this,this.eventHandler(this.handleEvent_64),true,true,false,false);
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_75,new import3.InlineArray4(4,'onSelect',(null as any),'onUnselect',(null as any)),this.eventHandler(this.handleEvent_75));
    this._SelectComponent_75_3.subscribe(this,this.eventHandler(this.handleEvent_75),true,true,false,false);
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_86,new import3.InlineArray4(4,'onSelect',(null as any),'onUnselect',(null as any)),this.eventHandler(this.handleEvent_86));
    this._SelectComponent_86_3.subscribe(this,this.eventHandler(this.handleEvent_86),true,true,false,false);
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_94,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_94));
    var disposable_9:Function = import3.subscribeToRenderElement(this,this._el_97,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_97));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._text_100,
      this._text_101
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.SelectComponent) && (20 === requestNodeIndex))) { return this._SelectComponent_20_3.context; }
    if (((token === import13.SelectComponent) && (31 === requestNodeIndex))) { return this._SelectComponent_31_3.context; }
    if (((token === import13.SelectComponent) && (42 === requestNodeIndex))) { return this._SelectComponent_42_3.context; }
    if (((token === import13.SelectComponent) && (53 === requestNodeIndex))) { return this._SelectComponent_53_3.context; }
    if (((token === import13.SelectComponent) && (64 === requestNodeIndex))) { return this._SelectComponent_64_3.context; }
    if (((token === import13.SelectComponent) && (75 === requestNodeIndex))) { return this._SelectComponent_75_3.context; }
    if (((token === import13.SelectComponent) && (86 === requestNodeIndex))) { return this._SelectComponent_86_3.context; }
    if (((token === import11.ModalComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._ModalComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'Change Multiple Defects';
    this._ModalComponent_0_3.check_title(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = 'defect-bulk-edit';
    this._ModalComponent_0_3.check_modalId(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = 'small';
    this._ModalComponent_0_3.check_modalSize(currVal_0_0_2,throwOnChange,false);
    this._ModalComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_20_0_0:any = 'select-defect-edit';
    this._SelectComponent_20_3.check_selectClass(currVal_20_0_0,throwOnChange,false);
    const currVal_20_0_1:any = 'defect-bulk-edit-multiComponents';
    this._SelectComponent_20_3.check_selectId(currVal_20_0_1,throwOnChange,false);
    const currVal_20_0_2:any = this.context.components;
    this._SelectComponent_20_3.check_items(currVal_20_0_2,throwOnChange,false);
    const currVal_20_0_3:any = true;
    this._SelectComponent_20_3.check_multiple(currVal_20_0_3,throwOnChange,false);
    const currVal_20_0_4:any = 'Select Component';
    this._SelectComponent_20_3.check_placeholder(currVal_20_0_4,throwOnChange,false);
    this._SelectComponent_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_31_0_0:any = 'select-defect-edit';
    this._SelectComponent_31_3.check_selectClass(currVal_31_0_0,throwOnChange,false);
    const currVal_31_0_1:any = 'defect-bulk-edit-status';
    this._SelectComponent_31_3.check_selectId(currVal_31_0_1,throwOnChange,false);
    const currVal_31_0_2:any = true;
    this._SelectComponent_31_3.check_allowClear(currVal_31_0_2,throwOnChange,false);
    const currVal_31_0_3:any = this.context.statuses;
    this._SelectComponent_31_3.check_items(currVal_31_0_3,throwOnChange,false);
    const currVal_31_0_4:any = 'Select Status';
    this._SelectComponent_31_3.check_placeholder(currVal_31_0_4,throwOnChange,false);
    this._SelectComponent_31_3.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_42_0_0:any = 'select-defect-edit';
    this._SelectComponent_42_3.check_selectClass(currVal_42_0_0,throwOnChange,false);
    const currVal_42_0_1:any = 'defect-bulk-edit-resolution';
    this._SelectComponent_42_3.check_selectId(currVal_42_0_1,throwOnChange,false);
    const currVal_42_0_2:any = true;
    this._SelectComponent_42_3.check_allowClear(currVal_42_0_2,throwOnChange,false);
    const currVal_42_0_3:any = this.context.resoluctions;
    this._SelectComponent_42_3.check_items(currVal_42_0_3,throwOnChange,false);
    const currVal_42_0_4:any = 'Select Resolution';
    this._SelectComponent_42_3.check_placeholder(currVal_42_0_4,throwOnChange,false);
    this._SelectComponent_42_3.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_53_0_0:any = 'select-defect-edit';
    this._SelectComponent_53_3.check_selectClass(currVal_53_0_0,throwOnChange,false);
    const currVal_53_0_1:any = 'defect-bulk-edit-multiVersions';
    this._SelectComponent_53_3.check_selectId(currVal_53_0_1,throwOnChange,false);
    const currVal_53_0_2:any = this.context.versions;
    this._SelectComponent_53_3.check_items(currVal_53_0_2,throwOnChange,false);
    const currVal_53_0_3:any = true;
    this._SelectComponent_53_3.check_multiple(currVal_53_0_3,throwOnChange,false);
    const currVal_53_0_4:any = 'Select Version';
    this._SelectComponent_53_3.check_placeholder(currVal_53_0_4,throwOnChange,false);
    this._SelectComponent_53_3.ngDoCheck(this,this._el_53,throwOnChange);
    const currVal_64_0_0:any = 'select-defect-edit';
    this._SelectComponent_64_3.check_selectClass(currVal_64_0_0,throwOnChange,false);
    const currVal_64_0_1:any = 'defect-bulk-edit-fixVersions';
    this._SelectComponent_64_3.check_selectId(currVal_64_0_1,throwOnChange,false);
    const currVal_64_0_2:any = this.context.fixVersions;
    this._SelectComponent_64_3.check_items(currVal_64_0_2,throwOnChange,false);
    const currVal_64_0_3:any = true;
    this._SelectComponent_64_3.check_multiple(currVal_64_0_3,throwOnChange,false);
    const currVal_64_0_4:any = 'Select FixVersion';
    this._SelectComponent_64_3.check_placeholder(currVal_64_0_4,throwOnChange,false);
    this._SelectComponent_64_3.ngDoCheck(this,this._el_64,throwOnChange);
    const currVal_75_0_0:any = 'select-defect-edit';
    this._SelectComponent_75_3.check_selectClass(currVal_75_0_0,throwOnChange,false);
    const currVal_75_0_1:any = 'defect-bulk-edit-priority';
    this._SelectComponent_75_3.check_selectId(currVal_75_0_1,throwOnChange,false);
    const currVal_75_0_2:any = true;
    this._SelectComponent_75_3.check_allowClear(currVal_75_0_2,throwOnChange,false);
    const currVal_75_0_3:any = this.context.priorities;
    this._SelectComponent_75_3.check_items(currVal_75_0_3,throwOnChange,false);
    const currVal_75_0_4:any = 'Select Priority';
    this._SelectComponent_75_3.check_placeholder(currVal_75_0_4,throwOnChange,false);
    this._SelectComponent_75_3.ngDoCheck(this,this._el_75,throwOnChange);
    const currVal_86_0_0:any = 'select-defect-edit';
    this._SelectComponent_86_3.check_selectClass(currVal_86_0_0,throwOnChange,false);
    const currVal_86_0_1:any = 'defect-bulk-edit-assignee';
    this._SelectComponent_86_3.check_selectId(currVal_86_0_1,throwOnChange,false);
    const currVal_86_0_2:any = true;
    this._SelectComponent_86_3.check_allowClear(currVal_86_0_2,throwOnChange,false);
    const currVal_86_0_3:any = 'Select Assignee';
    this._SelectComponent_86_3.check_placeholder(currVal_86_0_3,throwOnChange,false);
    const currVal_86_0_4:any = this.context.getSelect2Options('user');
    this._SelectComponent_86_3.check_editOptions(currVal_86_0_4,throwOnChange,false);
    this._SelectComponent_86_3.ngDoCheck(this,this._el_86,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_20.internalDetectChanges(throwOnChange);
    this.compView_31.internalDetectChanges(throwOnChange);
    this.compView_42.internalDetectChanges(throwOnChange);
    this.compView_53.internalDetectChanges(throwOnChange);
    this.compView_64.internalDetectChanges(throwOnChange);
    this.compView_75.internalDetectChanges(throwOnChange);
    this.compView_86.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._SelectComponent_20_3.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._SelectComponent_31_3.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._SelectComponent_42_3.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._SelectComponent_53_3.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._SelectComponent_64_3.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._SelectComponent_75_3.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._SelectComponent_86_3.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._ModalComponent_0_3.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_20.destroy();
    this.compView_31.destroy();
    this.compView_42.destroy();
    this.compView_53.destroy();
    this.compView_64.destroy();
    this.compView_75.destroy();
    this.compView_86.destroy();
    this._SelectComponent_20_3.ngOnDestroy();
    this._SelectComponent_31_3.ngOnDestroy();
    this._SelectComponent_42_3.ngOnDestroy();
    this._SelectComponent_53_3.ngOnDestroy();
    this._SelectComponent_64_3.ngOnDestroy();
    this._SelectComponent_75_3.ngOnDestroy();
    this._SelectComponent_86_3.ngOnDestroy();
    this._ModalComponent_0_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) { cb(this._el_2,ctx); }
    if (((nodeIndex == 0) && (ngContentIndex == 2))) { cb(this._el_92,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onClose')) {
      const pd_sub_0:any = ((<any>this.context.onCancelClearPrevious()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSelect')) {
      const pd_sub_0:any = ((<any>this.context.saveBulkEditValues($event,'multiComponents')) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onUnselect')) {
      const pd_sub_1:any = ((<any>this.context.unSelectField($event,'multiComponents')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_31(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSelect')) {
      const pd_sub_0:any = ((<any>this.context.saveBulkEditValues($event,'status')) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onUnselect')) {
      const pd_sub_1:any = ((<any>this.context.unSelectField($event,'status')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_42(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSelect')) {
      const pd_sub_0:any = ((<any>this.context.saveBulkEditValues($event,'resolution')) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onUnselect')) {
      const pd_sub_1:any = ((<any>this.context.unSelectField($event,'resolution')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_53(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSelect')) {
      const pd_sub_0:any = ((<any>this.context.saveBulkEditValues($event,'multiVersions')) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onUnselect')) {
      const pd_sub_1:any = ((<any>this.context.unSelectField($event,'multiVersions')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_64(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSelect')) {
      const pd_sub_0:any = ((<any>this.context.saveBulkEditValues($event,'fixVersions')) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onUnselect')) {
      const pd_sub_1:any = ((<any>this.context.unSelectField($event,'fixVersions')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_75(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSelect')) {
      const pd_sub_0:any = ((<any>this.context.saveBulkEditValues($event,'priority')) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onUnselect')) {
      const pd_sub_1:any = ((<any>this.context.unSelectField($event,'priority')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_86(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSelect')) {
      const pd_sub_0:any = ((<any>this.context.saveBulkEditValues($event,'assigned_to')) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onUnselect')) {
      const pd_sub_1:any = ((<any>this.context.unSelectField($event,'assigned_to')) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_94(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onCancelClearPrevious()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_97(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onBulkEdit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}