/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../../app/view/components/defects/defect_link/currently_linked/currently_linked_defects.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '../../../../../../../app/actions/grid.action';
import * as import7 from '../../../../../../../app/actions/defects.action';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/constants';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/http/src/http';
import * as import12 from '../../../../../../../app/services/pouch.db.service';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/router/src/router';
import * as import15 from '../../../../../../../app/view/components/grid/grid.component';
import * as import16 from '../../../../../../../app/actions/global.action';
import * as import17 from '../../../../../../../app/utils/scripts/utils';
import * as import18 from '../../../grid/grid.component.ngfactory';
import * as import19 from '../../../../../../../app/view/components/common/modal/modal.component';
import * as import20 from '../../../common/modal/modal.component.ngfactory';
import * as import21 from '@angular/common/src/pipes/i18n_select_pipe';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from '@angular/core/src/zone/ng_zone';
import * as import24 from '../../../../../../../app/services/toastr.service';
export class Wrapper_CurrentlyLinkedDefectsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CurrentlyLinkedDefectsComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  subscription0:any;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.CurrentlyLinkedDefectsComponent(p0,p1,p2,p3);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_testcaseId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.testcaseId = currValue;
      this._expr_0 = currValue;
    }
  }
  check_scheduleId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.scheduleId = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.onMapDefectsSchedule.subscribe(_eventHandler.bind(view,'onMapDefectsSchedule'))); }
  }
}
var renderType_CurrentlyLinkedDefectsComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_CurrentlyLinkedDefectsComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.CurrentlyLinkedDefectsComponent>;
  _GridAction_0_3:import6.GridAction;
  _DefectsAction_0_4:import7.DefectsAction;
  _CurrentlyLinkedDefectsComponent_0_5:Wrapper_CurrentlyLinkedDefectsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CurrentlyLinkedDefectsComponent_Host0,renderType_CurrentlyLinkedDefectsComponent_Host,import8.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'zee-currently-linked-defects',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CurrentlyLinkedDefectsComponent0(this.viewUtils,this,0,this._el_0);
    this._GridAction_0_3 = new import6.GridAction(this.injectorGet(import11.Http,this.parentIndex),this.injectorGet(import12.PouchDBPrefsServices,this.parentIndex));
    this._DefectsAction_0_4 = new import7.DefectsAction(this.injectorGet(import11.Http,this.parentIndex));
    this._CurrentlyLinkedDefectsComponent_0_5 = new Wrapper_CurrentlyLinkedDefectsComponent(this.injectorGet(import13.ActivatedRoute,this.parentIndex),this.injectorGet(import14.Router,this.parentIndex),this._GridAction_0_3,this._DefectsAction_0_4);
    this.compView_0.create(this._CurrentlyLinkedDefectsComponent_0_5.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import10.ComponentRef_<any>(0,this,this._el_0,this._CurrentlyLinkedDefectsComponent_0_5.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import6.GridAction) && (0 === requestNodeIndex))) { return this._GridAction_0_3; }
    if (((token === import7.DefectsAction) && (0 === requestNodeIndex))) { return this._DefectsAction_0_4; }
    if (((token === import0.CurrentlyLinkedDefectsComponent) && (0 === requestNodeIndex))) { return this._CurrentlyLinkedDefectsComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CurrentlyLinkedDefectsComponent_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._CurrentlyLinkedDefectsComponent_0_5.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CurrentlyLinkedDefectsComponent_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CurrentlyLinkedDefectsComponentNgFactory:import10.ComponentFactory<import0.CurrentlyLinkedDefectsComponent> = new import10.ComponentFactory<import0.CurrentlyLinkedDefectsComponent>('zee-currently-linked-defects',View_CurrentlyLinkedDefectsComponent_Host0,import0.CurrentlyLinkedDefectsComponent);
const styles_CurrentlyLinkedDefectsComponent:any[] = ([] as any[]);
var renderType_CurrentlyLinkedDefectsComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_CurrentlyLinkedDefectsComponent,{});
export class View_CurrentlyLinkedDefectsComponent0 extends import2.AppView<import0.CurrentlyLinkedDefectsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  compView_16:import2.AppView<import15.GridComponent>;
  _GridAction_16_3:import6.GridAction;
  _GlobalAction_16_4:import16.GlobalAction;
  _UtililtyFunctions_16_5:import17.UtililtyFunctions;
  _GridComponent_16_6:import18.Wrapper_GridComponent;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  compView_20:import2.AppView<import19.ModalComponent>;
  _ModalComponent_20_3:import20.Wrapper_ModalComponent;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  /*private*/ _expr_47:any;
  _pipe_i18nSelect_0:import21.I18nSelectPipe;
  _pipe_i18nSelect_0_0:any;
  /*private*/ _expr_50:any;
  _pipe_i18nSelect_0_1:any;
  /*private*/ _expr_52:any;
  _pipe_i18nSelect_0_2:any;
  /*private*/ _expr_54:any;
  _pipe_i18nSelect_0_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CurrentlyLinkedDefectsComponent0,renderType_CurrentlyLinkedDefectsComponent,import8.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways);
    this._expr_47 = import1.UNINITIALIZED;
    this._expr_50 = import1.UNINITIALIZED;
    this._expr_52 = import1.UNINITIALIZED;
    this._expr_54 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','currently-linked-defects-container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','currently-linked-defects-header'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h5',new import3.InlineArray2(2,'class','zee-content-subtitle'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Currently linked defects',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','delete-mapped-schedule floatRight'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray8(6,'disabled','disabled','id','delete-mapped-schedule-button','type','button'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Delete',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','currently-linked-defects-grid-container'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'grid',new import3.InlineArray2(2,'class','currently-linked-defects-grid'),(null as any));
    this.compView_16 = new import18.View_GridComponent0(this.viewUtils,this,16,this._el_16);
    this._GridAction_16_3 = new import6.GridAction(this.parentView.injectorGet(import11.Http,this.parentIndex),this.parentView.injectorGet(import12.PouchDBPrefsServices,this.parentIndex));
    this._GlobalAction_16_4 = new import16.GlobalAction(this.parentView.injectorGet(import11.Http,this.parentIndex));
    this._UtililtyFunctions_16_5 = new import17.UtililtyFunctions();
    this._GridComponent_16_6 = new import18.Wrapper_GridComponent(this._GridAction_16_3,this._GlobalAction_16_4,new import22.ElementRef(this._el_16),this._UtililtyFunctions_16_5,this.compView_16.ref,this.parentView.injectorGet(import23.NgZone,this.parentIndex),this.parentView.injectorGet(import14.Router,this.parentIndex),this.parentView.injectorGet(import12.PouchDBPrefsServices,this.parentIndex),this.parentView.injectorGet(import24.ToastrService,this.parentIndex));
    this._text_17 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_16.create(this._GridComponent_16_6.context);
    this._text_18 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_0,'zui-modal',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_20 = new import20.View_ModalComponent0(this.viewUtils,this,20,this._el_20);
    this._ModalComponent_20_3 = new import20.Wrapper_ModalComponent(new import22.ElementRef(this._el_20),this.compView_20.ref);
    this._text_21 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,(null as any),'zui-modal-body',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_24,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'',(null as any));
    this._text_27 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,(null as any),'zui-modal-footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'button',new import3.InlineArray4(4,'class','zui-btn zui-btn-sec','type','button'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_29,'button',new import3.InlineArray4(4,'class','zui-btn zui-btn-primary','type','button'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'',(null as any));
    this._text_36 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_20.create(this._ModalComponent_20_3.context);
    this._text_38 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_39 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_10));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray8(6,'onGridPrevClick',(null as any),'onGridNextClick',(null as any),'onGridRowSelection',(null as any)),this.eventHandler(this.handleEvent_16));
    this._GridComponent_16_6.subscribe(this,this.eventHandler(this.handleEvent_16),false,true,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray2(2,'onClose',(null as any)),this.eventHandler(this.handleEvent_20));
    this._ModalComponent_20_3.subscribe(this,this.eventHandler(this.handleEvent_20),true,false,false,false);
    this._pipe_i18nSelect_0 = new import21.I18nSelectPipe();
    this._pipe_i18nSelect_0_0 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    this._pipe_i18nSelect_0_1 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_31,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_31));
    this._pipe_i18nSelect_0_2 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_34,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_34));
    this._pipe_i18nSelect_0_3 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import6.GridAction) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._GridAction_16_3; }
    if (((token === import16.GlobalAction) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._GlobalAction_16_4; }
    if (((token === import17.UtililtyFunctions) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._UtililtyFunctions_16_5; }
    if (((token === import15.GridComponent) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._GridComponent_16_6.context; }
    if (((token === import19.ModalComponent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._ModalComponent_20_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_16_0_0:any = this.context.gridRows;
    this._GridComponent_16_6.check_rows(currVal_16_0_0,throwOnChange,false);
    const currVal_16_0_1:any = this.context._currentlyLinkedDefectsGridType;
    this._GridComponent_16_6.check_gridType(currVal_16_0_1,throwOnChange,false);
    const currVal_16_0_2:any = this.context.paginationOptions;
    this._GridComponent_16_6.check_paginationOptions(currVal_16_0_2,throwOnChange,false);
    this._GridComponent_16_6.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_20_0_0:any = true;
    this._ModalComponent_20_3.check_hideCloseIcon(currVal_20_0_0,throwOnChange,false);
    valUnwrapper.reset();
    const currVal_20_0_1:any = valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_0,this._pipe_i18nSelect_0.transform)('zephyr.defect.delete.mapped.schedule.header',this.context.i18nMessages));
    this._ModalComponent_20_3.check_title(currVal_20_0_1,throwOnChange,valUnwrapper.hasWrappedValue);
    const currVal_20_0_2:any = 'delete-mapped-schedule-modal';
    this._ModalComponent_20_3.check_modalId(currVal_20_0_2,throwOnChange,false);
    const currVal_20_0_3:any = 'small';
    this._ModalComponent_20_3.check_modalSize(currVal_20_0_3,throwOnChange,false);
    this._ModalComponent_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_47:any = 'btn btn-secondary';
    if (import3.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementProperty(this._el_10,'className',currVal_47);
      this._expr_47 = currVal_47;
    }
    valUnwrapper.reset();
    const currVal_50:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_1,this._pipe_i18nSelect_0.transform)('zephyr.defect.delete.mapped.schedule.message',this.context.i18nMessages)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_50,currVal_50))) {
      this.renderer.setText(this._text_26,currVal_50);
      this._expr_50 = currVal_50;
    }
    valUnwrapper.reset();
    const currVal_52:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_2,this._pipe_i18nSelect_0.transform)('zephyr.button.cancel',this.context.i18nMessages)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_52,currVal_52))) {
      this.renderer.setText(this._text_32,currVal_52);
      this._expr_52 = currVal_52;
    }
    valUnwrapper.reset();
    const currVal_54:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_3,this._pipe_i18nSelect_0.transform)('zephyr.button.delete',this.context.i18nMessages)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_54,currVal_54))) {
      this.renderer.setText(this._text_35,currVal_54);
      this._expr_54 = currVal_54;
    }
    this.compView_16.internalDetectChanges(throwOnChange);
    this.compView_20.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._GridComponent_16_6.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._ModalComponent_20_3.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this.compView_16.destroy();
    this.compView_20.destroy();
    this._GridComponent_16_6.ngOnDestroy();
    this._ModalComponent_20_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 20) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 20) && (ngContentIndex == 1))) { cb(this._el_22,ctx); }
    if (((nodeIndex == 20) && (ngContentIndex == 2))) { cb(this._el_29,ctx); }
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.showDeleteMappedScheduleModal()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onGridPrevClick')) {
      const pd_sub_0:any = ((<any>this.context.gridPrevClick()) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onGridNextClick')) {
      const pd_sub_1:any = ((<any>this.context.gridNextClick()) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'onGridRowSelection')) {
      const pd_sub_2:any = ((<any>this.context.gridRowSelection($event)) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onClose')) {
      const pd_sub_0:any = ((<any>this.context.hideDeleteMappedScheduleModal()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_31(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.hideDeleteMappedScheduleModal()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_34(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.deleteMappedSchedule()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}