/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../app/view/components/requirements/operations/requirement_export.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/core/src/linker/query_list';
import * as import10 from '../../../../../../app/view/components/common/export/export.component';
import * as import11 from '../../../../../../app/actions/report.action';
import * as import12 from '../../../../../../app/actions/admin.action';
import * as import13 from '../../common/export/export.component.ngfactory';
import * as import14 from '@angular/common/src/pipes/i18n_select_pipe';
import * as import15 from '@angular/http/src/http';
import * as import16 from '../../../../../../app/services/pouch.db.service';
export class Wrapper_RequirementExportComponent {
  /*private*/ _eventHandler:Function;
  context:import0.RequirementExportComponent;
  /*private*/ _changed:boolean;
  /*private*/ _changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor() {
    this._changed = false;
    this._changes = {};
    this.context = new import0.RequirementExportComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    this._expr_5 = import1.UNINITIALIZED;
    this._expr_6 = import1.UNINITIALIZED;
    this._expr_7 = import1.UNINITIALIZED;
    this._expr_8 = import1.UNINITIALIZED;
    this._expr_9 = import1.UNINITIALIZED;
    this._expr_10 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  check_fieldOptions(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.fieldOptions = currValue;
      this._changes['fieldOptions'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  check_reqIDs(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.reqIDs = currValue;
      this._changes['reqIDs'] = new import1.SimpleChange(this._expr_1,currValue);
      this._expr_1 = currValue;
    }
  }
  check_reqCatalogTreeId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.reqCatalogTreeId = currValue;
      this._changes['reqCatalogTreeId'] = new import1.SimpleChange(this._expr_2,currValue);
      this._expr_2 = currValue;
    }
  }
  check_isDisabled(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.isDisabled = currValue;
      this._changes['isDisabled'] = new import1.SimpleChange(this._expr_3,currValue);
      this._expr_3 = currValue;
    }
  }
  check_releaseId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_4,currValue))) {
      this._changed = true;
      this.context.releaseId = currValue;
      this._changes['releaseId'] = new import1.SimpleChange(this._expr_4,currValue);
      this._expr_4 = currValue;
    }
  }
  check_inRelease(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_5,currValue))) {
      this._changed = true;
      this.context.inRelease = currValue;
      this._changes['inRelease'] = new import1.SimpleChange(this._expr_5,currValue);
      this._expr_5 = currValue;
    }
  }
  check_isSearchView(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_6,currValue))) {
      this._changed = true;
      this.context.isSearchView = currValue;
      this._changes['isSearchView'] = new import1.SimpleChange(this._expr_6,currValue);
      this._expr_6 = currValue;
    }
  }
  check_isGlobal(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_7,currValue))) {
      this._changed = true;
      this.context.isGlobal = currValue;
      this._changes['isGlobal'] = new import1.SimpleChange(this._expr_7,currValue);
      this._expr_7 = currValue;
    }
  }
  check_projectId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_8,currValue))) {
      this._changed = true;
      this.context.projectId = currValue;
      this._changes['projectId'] = new import1.SimpleChange(this._expr_8,currValue);
      this._expr_8 = currValue;
    }
  }
  check_isAdvancedSearch(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_9,currValue))) {
      this._changed = true;
      this.context.isAdvancedSearch = currValue;
      this._changes['isAdvancedSearch'] = new import1.SimpleChange(this._expr_9,currValue);
      this._expr_9 = currValue;
    }
  }
  check_searchText(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_10,currValue))) {
      this._changed = true;
      this.context.searchText = currValue;
      this._changes['searchText'] = new import1.SimpleChange(this._expr_10,currValue);
      this._expr_10 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if (changed) {
      this.context.ngOnChanges(this._changes);
      this._changes = {};
    } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_RequirementExportComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_RequirementExportComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.RequirementExportComponent>;
  _RequirementExportComponent_0_3:Wrapper_RequirementExportComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_RequirementExportComponent_Host0,renderType_RequirementExportComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'zee-export-dialog-requirement',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_RequirementExportComponent0(this.viewUtils,this,0,this._el_0);
    this._RequirementExportComponent_0_3 = new Wrapper_RequirementExportComponent();
    this.compView_0.create(this._RequirementExportComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._RequirementExportComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.RequirementExportComponent) && (0 === requestNodeIndex))) { return this._RequirementExportComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RequirementExportComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._RequirementExportComponent_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._RequirementExportComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const RequirementExportComponentNgFactory:import8.ComponentFactory<import0.RequirementExportComponent> = new import8.ComponentFactory<import0.RequirementExportComponent>('zee-export-dialog-requirement',View_RequirementExportComponent_Host0,import0.RequirementExportComponent);
const styles_RequirementExportComponent:any[] = ([] as any[]);
var renderType_RequirementExportComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_RequirementExportComponent,{});
export class View_RequirementExportComponent0 extends import2.AppView<import0.RequirementExportComponent> {
  _viewQuery_ExportComponent_0:import9.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  compView_36:import2.AppView<import10.ExportComponent>;
  _ReportAction_36_3:import11.ReportAction;
  _AdminAction_36_4:import12.AdminAction;
  _ExportComponent_36_5:import13.Wrapper_ExportComponent;
  _text_37:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  _pipe_i18nSelect_0:import14.I18nSelectPipe;
  _pipe_i18nSelect_0_0:any;
  /*private*/ _expr_57:any;
  _pipe_i18nSelect_0_1:any;
  /*private*/ _expr_59:any;
  _pipe_i18nSelect_0_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_RequirementExportComponent0,renderType_RequirementExportComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_43 = import1.UNINITIALIZED;
    this._expr_44 = import1.UNINITIALIZED;
    this._expr_45 = import1.UNINITIALIZED;
    this._expr_46 = import1.UNINITIALIZED;
    this._expr_47 = import1.UNINITIALIZED;
    this._expr_48 = import1.UNINITIALIZED;
    this._expr_49 = import1.UNINITIALIZED;
    this._expr_50 = import1.UNINITIALIZED;
    this._expr_51 = import1.UNINITIALIZED;
    this._expr_52 = import1.UNINITIALIZED;
    this._expr_53 = import1.UNINITIALIZED;
    this._expr_54 = import1.UNINITIALIZED;
    this._expr_57 = import1.UNINITIALIZED;
    this._expr_59 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_ExportComponent_0 = new import9.QueryList<any>();
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'button',new import3.InlineArray4(4,'data-toggle','modal','type','button'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray8(6,'data-backdrop','static','role','dialog','tabindex','-1'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'button',new import3.InlineArray8(6,'class','close','data-dismiss','modal','type','button'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'×',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_9,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_7,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'style','text-align: center;'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'button',new import3.InlineArray4(4,'class','zui-btn zui-btn-sec','data-dismiss','modal'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_20,'button',new import3.InlineArray2(2,'class','zui-btn zui-btn-primary'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'',(null as any));
    this._text_27 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_20,'button',new import3.InlineArray2(2,'class','zui-btn zui-btn-primary'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_20,'\n\n                ',(null as any));
    this._text_31 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,parentRenderNode,'zui-export',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_36 = new import13.View_ExportComponent0(this.viewUtils,this,36,this._el_36);
    this._ReportAction_36_3 = new import11.ReportAction(this.parentView.injectorGet(import15.Http,this.parentIndex));
    this._AdminAction_36_4 = new import12.AdminAction(this.parentView.injectorGet(import15.Http,this.parentIndex),this.parentView.injectorGet(import16.PouchDBPrefsServices,this.parentIndex));
    this._ExportComponent_36_5 = new import13.Wrapper_ExportComponent(this._ReportAction_36_3,this._AdminAction_36_4,this.compView_36.ref);
    this.compView_36.create(this._ExportComponent_36_5.context);
    this._text_37 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this._pipe_i18nSelect_0 = new import14.I18nSelectPipe();
    this._pipe_i18nSelect_0_0 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_25,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_25));
    this._pipe_i18nSelect_0_1 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_28));
    this._pipe_i18nSelect_0_2 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    this._viewQuery_ExportComponent_0.reset([this._ExportComponent_36_5.context]);
    this.context.exportUI = this._viewQuery_ExportComponent_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.ReportAction) && (36 === requestNodeIndex))) { return this._ReportAction_36_3; }
    if (((token === import12.AdminAction) && (36 === requestNodeIndex))) { return this._AdminAction_36_4; }
    if (((token === import10.ExportComponent) && (36 === requestNodeIndex))) { return this._ExportComponent_36_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_36_0_0:any = this.context.fieldOptions;
    this._ExportComponent_36_5.check_fieldOptions(currVal_36_0_0,throwOnChange,false);
    const currVal_36_0_1:any = this.context.isSearchView;
    this._ExportComponent_36_5.check_isSearchView(currVal_36_0_1,throwOnChange,false);
    if (this._ExportComponent_36_5.ngDoCheck(this,this._el_36,throwOnChange)) { this.compView_36.markAsCheckOnce(); }
    const currVal_43:any = 'zui-btn zui-btn-tertiary';
    if (import3.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementProperty(this._el_0,'className',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = import3.inlineInterpolate(1,'zui-export-modal-trigger-',this.context.fieldOptions.id,'');
    if (import3.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementProperty(this._el_0,'id',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = import3.inlineInterpolate(1,'',this.context.fieldOptions.header,'');
    if (import3.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setText(this._text_1,currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = 'modal fade zui-export-modal-choice';
    if (import3.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementProperty(this._el_3,'className',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = import3.inlineInterpolate(1,'zui-export-modal-',this.context.fieldOptions.id,'-choice');
    if (import3.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementProperty(this._el_3,'id',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = 'modal-dialog small';
    if (import3.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementProperty(this._el_5,'className',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = 'modal-content';
    if (import3.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementProperty(this._el_7,'className',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = 'modal-header';
    if (import3.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementProperty(this._el_9,'className',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = 'modal-title';
    if (import3.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementProperty(this._el_14,'className',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = import3.inlineInterpolate(1,'',this.context.fieldOptions.choiceTitle,'');
    if (import3.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setText(this._text_15,currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = 'modal-body';
    if (import3.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementProperty(this._el_18,'className',currVal_53);
      this._expr_53 = currVal_53;
    }
    valUnwrapper.reset();
    const currVal_54:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_0,this._pipe_i18nSelect_0.transform)('zephyr.button.cancel',this.context.i18nMessages)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_54,currVal_54))) {
      this.renderer.setText(this._text_23,currVal_54);
      this._expr_54 = currVal_54;
    }
    valUnwrapper.reset();
    const currVal_57:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_1,this._pipe_i18nSelect_0.transform)('zephyr.export.choice.traceability',this.context.i18nMessages)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_57,currVal_57))) {
      this.renderer.setText(this._text_26,currVal_57);
      this._expr_57 = currVal_57;
    }
    valUnwrapper.reset();
    const currVal_59:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_2,this._pipe_i18nSelect_0.transform)('zephyr.export.choice.requirement',this.context.i18nMessages)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_59,currVal_59))) {
      this.renderer.setText(this._text_29,currVal_59);
      this._expr_59 = currVal_59;
    }
    this.compView_36.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._ExportComponent_36_5.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_36.destroy();
    this._ExportComponent_36_5.ngOnDestroy();
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.showReqChoiceModal($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_25(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.exportEntireTrac()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.exportReqOnly()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}