/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../app/view/components/release_setup/release_form/release_form.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../../../../../app/actions/release.action';
import * as import6 from '../../../../../../app/actions/defects.action';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/constants';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/forms/src/form_builder';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
import * as import14 from '../../../../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import15 from '../../../../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import18 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import19 from '../../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/common/src/directives/ng_if';
import * as import22 from '../../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import23 from '../../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import24 from '../../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import25 from '../../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import26 from '../../../../../node_modules/@angular/forms/src/directives/checkbox_value_accessor.ngfactory';
import * as import27 from '../../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_directive.ngfactory';
import * as import28 from '../../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import29 from '../../../../../../app/view/components/common/calendar/calendar.component';
import * as import30 from '../../common/calendar/calendar.component.ngfactory';
import * as import31 from '../../../../../../app/view/components/form_dirty_dialog/form_dirty_dialog.component';
import * as import32 from '../../form_dirty_dialog/form_dirty_dialog.component.ngfactory';
import * as import33 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import34 from '@angular/forms/src/directives/default_value_accessor';
import * as import35 from '@angular/forms/src/directives/control_value_accessor';
import * as import36 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import37 from '@angular/forms/src/directives/ng_control';
import * as import38 from '@angular/forms/src/directives/ng_control_status';
import * as import39 from '@angular/forms/src/directives/checkbox_value_accessor';
import * as import40 from '@angular/common/src/directives/ng_for';
import * as import41 from '@angular/forms/src/directives/reactive_directives/form_control_directive';
import * as import42 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import43 from '@angular/forms/src/directives/control_container';
export class Wrapper_ReleaseFormComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ReleaseFormComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.ReleaseFormComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ReleaseFormComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ReleaseFormComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ReleaseFormComponent>;
  _ReleaseAction_0_3:import5.ReleaseAction;
  _DefectsAction_0_4:import6.DefectsAction;
  _ReleaseFormComponent_0_5:Wrapper_ReleaseFormComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ReleaseFormComponent_Host0,renderType_ReleaseFormComponent_Host,import7.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'release-form',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ReleaseFormComponent0(this.viewUtils,this,0,this._el_0);
    this._ReleaseAction_0_3 = new import5.ReleaseAction(this.injectorGet(import10.Http,this.parentIndex));
    this._DefectsAction_0_4 = new import6.DefectsAction(this.injectorGet(import10.Http,this.parentIndex));
    this._ReleaseFormComponent_0_5 = new Wrapper_ReleaseFormComponent(this._ReleaseAction_0_3,this.injectorGet(import11.FormBuilder,this.parentIndex),this.compView_0.ref,this._DefectsAction_0_4);
    this.compView_0.create(this._ReleaseFormComponent_0_5.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._ReleaseFormComponent_0_5.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.ReleaseAction) && (0 === requestNodeIndex))) { return this._ReleaseAction_0_3; }
    if (((token === import6.DefectsAction) && (0 === requestNodeIndex))) { return this._DefectsAction_0_4; }
    if (((token === import0.ReleaseFormComponent) && (0 === requestNodeIndex))) { return this._ReleaseFormComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ReleaseFormComponent_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._ReleaseFormComponent_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ReleaseFormComponentNgFactory:import9.ComponentFactory<import0.ReleaseFormComponent> = new import9.ComponentFactory<import0.ReleaseFormComponent>('release-form',View_ReleaseFormComponent_Host0,import0.ReleaseFormComponent);
const styles_ReleaseFormComponent:any[] = ([] as any[]);
class View_ReleaseFormComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ReleaseFormComponent1,renderType_ReleaseFormComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,' Edit Release ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ReleaseFormComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ReleaseFormComponent2,renderType_ReleaseFormComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,' Add Release ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ReleaseFormComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ReleaseFormComponent3,renderType_ReleaseFormComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray2(2,'class','field-value italic-font-style'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Auto Generated ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ReleaseFormComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ReleaseFormComponent4,renderType_ReleaseFormComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray2(2,'class','field-value'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.context.release.id,' ');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ReleaseFormComponent5 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import14.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import15.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ReleaseFormComponent5,renderType_ReleaseFormComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import13.UNINITIALIZED;
    this._expr_5 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_0_3 = new import14.Wrapper_NgSelectOption(new import16.ElementRef(this._el_0),this.renderer,(<View_ReleaseFormComponent0>this.parentView)._SelectControlValueAccessor_70_3.context);
    this._NgSelectMultipleOption_0_4 = new import15.Wrapper_NgSelectMultipleOption(new import16.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import18.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgSelectOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgSelectMultipleOption_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_4:any = this.context.$implicit.key;
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementAttribute(this._el_0,'value',((currVal_4 == null)? (null as any): currVal_4.toString()));
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import3.inlineInterpolate(1,'',this.context.$implicit.value,'');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_1,currVal_5);
      this._expr_5 = currVal_5;
    }
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ReleaseFormComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ReleaseFormComponent7,renderType_ReleaseFormComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray8(6,'class','zui-btn zui-btn-sec','data-dismiss','modal','type','button'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.confirmationObject.cancelButtonText,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ReleaseFormComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _vc_26:import12.ViewContainer;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import19.Wrapper_NgIf;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ReleaseFormComponent6,renderType_ReleaseFormComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_37 = import13.UNINITIALIZED;
    this._expr_38 = import13.UNINITIALIZED;
    this._expr_39 = import13.UNINITIALIZED;
    this._expr_40 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray16(14,'aria-hidden','true','aria-labelledby','myModalLabel','class','modal fade','data-backdrop','static','id','confirmation-modal-form','role','dialog','tabindex','-1'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray4(4,'class','modal-dialog','role','document'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','modal-content'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','modal-header'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'button',new import3.InlineArray8(8,'aria-label','Close','class','close','data-dismiss','modal','type','button'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'span',new import3.InlineArray2(2,'aria-hidden','true'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'×',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n                    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_6,'h2',new import3.InlineArray4(4,'class','modal-title','id','myModalLabel'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','modal-body'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._text_23 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','modal-footer'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                  ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._vc_26 = new import12.ViewContainer(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import20.TemplateRef_(this,26,this._anchor_26);
    this._NgIf_26_6 = new import19.Wrapper_NgIf(this._vc_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_24,'\n                  ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_24,'button',new import3.InlineArray4(4,'class','zui-btn zui-btn-primary','type','button'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n\n\n                ',(null as any));
    this._text_31 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_28));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import21.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_26_0_0:any = this.parentView.context.confirmationObject.showCancelButton;
    this._NgIf_26_6.check_ngIf(currVal_26_0_0,throwOnChange,false);
    this._NgIf_26_6.ngDoCheck(this,this._anchor_26,throwOnChange);
    this._vc_26.detectChangesInNestedViews(throwOnChange);
    const currVal_37:any = import3.inlineInterpolate(1,'',this.parentView.context.confirmationObject.heading,' ');
    if (import3.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setText(this._text_15,currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = import3.inlineInterpolate(1,' ',this.parentView.context.confirmationObject.text,' ');
    if (import3.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setText(this._text_21,currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this.parentView.context.confirmationObject.action;
    if (import3.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementAttribute(this._el_28,'value',((currVal_39 == null)? (null as any): currVal_39.toString()));
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = import3.inlineInterpolate(1,'',this.parentView.context.confirmationObject.buttonText,'');
    if (import3.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setText(this._text_29,currVal_40);
      this._expr_40 = currVal_40;
    }
  }
  destroyInternal():void {
    this._vc_26.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 26)) { return new View_ReleaseFormComponent7(this.viewUtils,this,26,this._anchor_26,this._vc_26); }
    return (null as any);
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.confirmationActionCall($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_ReleaseFormComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_ReleaseFormComponent,{});
export class View_ReleaseFormComponent0 extends import1.AppView<import0.ReleaseFormComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import12.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import19.Wrapper_NgIf;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _vc_6:import12.ViewContainer;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import19.Wrapper_NgIf;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _FormGroupDirective_9_3:import22.Wrapper_FormGroupDirective;
  _ControlContainer_9_4:any;
  _NgControlStatusGroup_9_5:import23.Wrapper_NgControlStatusGroup;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import24.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_23_4:any[];
  _FormControlName_23_5:import25.Wrapper_FormControlName;
  _NgControl_23_6:any;
  _NgControlStatus_23_7:import23.Wrapper_NgControlStatus;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _DefaultValueAccessor_31_3:import24.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_31_4:any[];
  _FormControlName_31_5:import25.Wrapper_FormControlName;
  _NgControl_31_6:any;
  _NgControlStatus_31_7:import23.Wrapper_NgControlStatus;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _anchor_40:any;
  /*private*/ _vc_40:import12.ViewContainer;
  _TemplateRef_40_5:any;
  _NgIf_40_6:import19.Wrapper_NgIf;
  _text_41:any;
  _anchor_42:any;
  /*private*/ _vc_42:import12.ViewContainer;
  _TemplateRef_42_5:any;
  _NgIf_42_6:import19.Wrapper_NgIf;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _CheckboxControlValueAccessor_52_3:import26.Wrapper_CheckboxControlValueAccessor;
  _NG_VALUE_ACCESSOR_52_4:any[];
  _FormControlName_52_5:import25.Wrapper_FormControlName;
  _NgControl_52_6:any;
  _NgControlStatus_52_7:import23.Wrapper_NgControlStatus;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _SelectControlValueAccessor_70_3:import14.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_70_4:any[];
  _FormControlDirective_70_5:import27.Wrapper_FormControlDirective;
  _NgControl_70_6:any;
  _NgControlStatus_70_7:import23.Wrapper_NgControlStatus;
  _text_71:any;
  _el_72:any;
  _NgSelectOption_72_3:import14.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_72_4:import15.Wrapper_NgSelectMultipleOption;
  _text_73:any;
  _text_74:any;
  _anchor_75:any;
  /*private*/ _vc_75:import12.ViewContainer;
  _TemplateRef_75_5:any;
  _NgFor_75_6:import28.Wrapper_NgFor;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _el_91:any;
  compView_91:import1.AppView<import29.CalendarComponent>;
  _CalendarComponent_91_3:import30.Wrapper_CalendarComponent;
  _text_92:any;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _el_103:any;
  compView_103:import1.AppView<import29.CalendarComponent>;
  _CalendarComponent_103_3:import30.Wrapper_CalendarComponent;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  _text_107:any;
  _text_108:any;
  _text_109:any;
  _el_110:any;
  _text_111:any;
  _el_112:any;
  _text_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _text_117:any;
  _text_118:any;
  _text_119:any;
  _el_120:any;
  compView_120:import1.AppView<import31.FormDirtyDialogComponent>;
  _FormDirtyDialogComponent_120_3:import32.Wrapper_FormDirtyDialogComponent;
  _text_121:any;
  _text_122:any;
  _text_123:any;
  _anchor_124:any;
  /*private*/ _vc_124:import12.ViewContainer;
  _TemplateRef_124_5:any;
  _NgIf_124_6:import19.Wrapper_NgIf;
  _text_125:any;
  _text_126:any;
  /*private*/ _expr_176:any;
  /*private*/ _expr_177:any;
  /*private*/ _expr_178:any;
  /*private*/ _expr_179:any;
  /*private*/ _expr_180:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ReleaseFormComponent0,renderType_ReleaseFormComponent,import7.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways);
    this._expr_176 = import13.UNINITIALIZED;
    this._expr_177 = import13.UNINITIALIZED;
    this._expr_178 = import13.UNINITIALIZED;
    this._expr_179 = import13.UNINITIALIZED;
    this._expr_180 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','release-form subform clearfix'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h5',new import3.InlineArray2(2,'class','zui-panel-heading'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_4 = new import12.ViewContainer(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import20.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import19.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_6 = new import12.ViewContainer(6,2,this,this._anchor_6);
    this._TemplateRef_6_5 = new import20.TemplateRef_(this,6,this._anchor_6);
    this._NgIf_6_6 = new import19.Wrapper_NgIf(this._vc_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_0,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._FormGroupDirective_9_3 = new import22.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_9_4 = this._FormGroupDirective_9_3.context;
    this._NgControlStatusGroup_9_5 = new import23.Wrapper_NgControlStatusGroup(this._ControlContainer_9_4);
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','col-md-6 col-xs-12'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'label',new import3.InlineArray2(2,'for','release-name'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Name',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'span',new import3.InlineArray2(2,'class','input-required'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'*',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,' :',(null as any));
    this._text_22 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_15,'input',new import3.InlineArray16(14,'class','form-control','formControlName','name','id','release-name','name','name','placeholder','Enter name','title','Name is a required field and should be less than 50 charcters','type','text'),(null as any));
    this._DefaultValueAccessor_23_3 = new import24.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_23));
    this._NG_VALUE_ACCESSOR_23_4 = [this._DefaultValueAccessor_23_3.context];
    this._FormControlName_23_5 = new import25.Wrapper_FormControlName(this._ControlContainer_9_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_23_4);
    this._NgControl_23_6 = this._FormControlName_23_5.context;
    this._NgControlStatus_23_7 = new import23.Wrapper_NgControlStatus(this._NgControl_23_6);
    this._text_24 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._text_25 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'label',new import3.InlineArray2(2,'for','release-description'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Description :',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_26,'textarea',new import3.InlineArray16(12,'class','form-control zui-textarea','formControlName','description','id','release-description','name','description','placeholder','Enter description','title','Length should be less than 250 characters'),(null as any));
    this._DefaultValueAccessor_31_3 = new import24.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_31));
    this._NG_VALUE_ACCESSOR_31_4 = [this._DefaultValueAccessor_31_3.context];
    this._FormControlName_31_5 = new import25.Wrapper_FormControlName(this._ControlContainer_9_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_31_4);
    this._NgControl_31_6 = this._FormControlName_31_5.context;
    this._NgControlStatus_31_7 = new import23.Wrapper_NgControlStatus(this._NgControl_31_6);
    this._text_32 = this.renderer.createText(this._el_31,' ',(null as any));
    this._text_33 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._text_34 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'label',new import3.InlineArray2(2,'for','release-id'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'ID :',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._anchor_40 = this.renderer.createTemplateAnchor(this._el_35,(null as any));
    this._vc_40 = new import12.ViewContainer(40,35,this,this._anchor_40);
    this._TemplateRef_40_5 = new import20.TemplateRef_(this,40,this._anchor_40);
    this._NgIf_40_6 = new import19.Wrapper_NgIf(this._vc_40.vcRef,this._TemplateRef_40_5);
    this._text_41 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._anchor_42 = this.renderer.createTemplateAnchor(this._el_35,(null as any));
    this._vc_42 = new import12.ViewContainer(42,35,this,this._anchor_42);
    this._TemplateRef_42_5 = new import20.TemplateRef_(this,42,this._anchor_42);
    this._NgIf_42_6 = new import19.Wrapper_NgIf(this._vc_42.vcRef,this._TemplateRef_42_5);
    this._text_43 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._text_44 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n                    ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_45,'label',new import3.InlineArray2(2,'for','release-status'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'Hide:',(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n                    ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_45,'div',new import3.InlineArray2(2,'class','zui-checkbox2'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n                        ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'input',new import3.InlineArray16(10,'class','form-control','formControlName','status','id','release-status','name','status','type','checkbox'),(null as any));
    this._CheckboxControlValueAccessor_52_3 = new import26.Wrapper_CheckboxControlValueAccessor(this.renderer,new import16.ElementRef(this._el_52));
    this._NG_VALUE_ACCESSOR_52_4 = [this._CheckboxControlValueAccessor_52_3.context];
    this._FormControlName_52_5 = new import25.Wrapper_FormControlName(this._ControlContainer_9_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_52_4);
    this._NgControl_52_6 = this._FormControlName_52_5.context;
    this._NgControlStatus_52_7 = new import23.Wrapper_NgControlStatus(this._NgControl_52_6);
    this._text_53 = this.renderer.createText(this._el_50,'\n                        ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_50,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_55 = this.renderer.createText(this._el_50,'\n                    ',(null as any));
    this._text_56 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._text_57 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._text_58 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','col-md-6 col-xs-12'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'\n                ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_59,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n                    ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_61,'label',new import3.InlineArray2(2,'for','project-externalSystem'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'Map external defect project :',(null as any));
    this._text_65 = this.renderer.createText(this._el_61,'\n                    ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_61,'div',new import3.InlineArray2(2,'class','field-value'),(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'\n                        ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_66,'div',new import3.InlineArray2(2,'class','zui-select'),(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'\n                            ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_68,'select',new import3.InlineArray2(2,'class','form-control'),(null as any));
    this._SelectControlValueAccessor_70_3 = new import14.Wrapper_SelectControlValueAccessor(this.renderer,new import16.ElementRef(this._el_70));
    this._NG_VALUE_ACCESSOR_70_4 = [this._SelectControlValueAccessor_70_3.context];
    this._FormControlDirective_70_5 = new import27.Wrapper_FormControlDirective((null as any),(null as any),this._NG_VALUE_ACCESSOR_70_4);
    this._NgControl_70_6 = this._FormControlDirective_70_5.context;
    this._NgControlStatus_70_7 = new import23.Wrapper_NgControlStatus(this._NgControl_70_6);
    this._text_71 = this.renderer.createText(this._el_70,'\n                                ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_70,'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_72_3 = new import14.Wrapper_NgSelectOption(new import16.ElementRef(this._el_72),this.renderer,this._SelectControlValueAccessor_70_3.context);
    this._NgSelectMultipleOption_72_4 = new import15.Wrapper_NgSelectMultipleOption(new import16.ElementRef(this._el_72),this.renderer,(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'Select Project',(null as any));
    this._text_74 = this.renderer.createText(this._el_70,'\n                                ',(null as any));
    this._anchor_75 = this.renderer.createTemplateAnchor(this._el_70,(null as any));
    this._vc_75 = new import12.ViewContainer(75,70,this,this._anchor_75);
    this._TemplateRef_75_5 = new import20.TemplateRef_(this,75,this._anchor_75);
    this._NgFor_75_6 = new import28.Wrapper_NgFor(this._vc_75.vcRef,this._TemplateRef_75_5,this.parentView.injectorGet(import33.IterableDiffers,this.parentIndex),this.ref);
    this._text_76 = this.renderer.createText(this._el_70,'\n                            ',(null as any));
    this._text_77 = this.renderer.createText(this._el_68,'\n                        ',(null as any));
    this._text_78 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._text_79 = this.renderer.createText(this._el_61,'\n                ',(null as any));
    this._text_80 = this.renderer.createText(this._el_59,'\n                ',(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_59,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'\n                    ',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_81,'label',new import3.InlineArray2(2,'for','release-startdate'),(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'Start Date',(null as any));
    this._el_85 = import3.createRenderElement(this.renderer,this._el_83,'span',new import3.InlineArray2(2,'class','input-required'),(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'*',(null as any));
    this._text_87 = this.renderer.createText(this._el_83,' :',(null as any));
    this._text_88 = this.renderer.createText(this._el_81,'\n                    ',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_81,'div',new import3.InlineArray8(6,'class','datepicker-wrap','id','release-startdate','title','Start date is a required field. It should be after project\'s start date and before project\'s end date'),(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'\n                        ',(null as any));
    this._el_91 = import3.createRenderElement(this.renderer,this._el_89,'calendar',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_91 = new import30.View_CalendarComponent0(this.viewUtils,this,91,this._el_91);
    this._CalendarComponent_91_3 = new import30.Wrapper_CalendarComponent(new import16.ElementRef(this._el_91));
    this._text_92 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this.compView_91.create(this._CalendarComponent_91_3.context);
    this._text_93 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._text_94 = this.renderer.createText(this._el_81,'\n                ',(null as any));
    this._text_95 = this.renderer.createText(this._el_59,'\n                ',(null as any));
    this._el_96 = import3.createRenderElement(this.renderer,this._el_59,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_97 = this.renderer.createText(this._el_96,'\n                    ',(null as any));
    this._el_98 = import3.createRenderElement(this.renderer,this._el_96,'label',new import3.InlineArray2(2,'for','release-enddate'),(null as any));
    this._text_99 = this.renderer.createText(this._el_98,'End Date :',(null as any));
    this._text_100 = this.renderer.createText(this._el_96,'\n                    ',(null as any));
    this._el_101 = import3.createRenderElement(this.renderer,this._el_96,'div',new import3.InlineArray8(6,'class','datepicker-wrap','id','release-enddatee','title','End date should be after release start date and before project\'s end date'),(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'\n                        ',(null as any));
    this._el_103 = import3.createRenderElement(this.renderer,this._el_101,'calendar',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_103 = new import30.View_CalendarComponent0(this.viewUtils,this,103,this._el_103);
    this._CalendarComponent_103_3 = new import30.Wrapper_CalendarComponent(new import16.ElementRef(this._el_103));
    this._text_104 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this.compView_103.create(this._CalendarComponent_103_3.context);
    this._text_105 = this.renderer.createText(this._el_101,'\n                    ',(null as any));
    this._text_106 = this.renderer.createText(this._el_96,'\n                ',(null as any));
    this._text_107 = this.renderer.createText(this._el_59,'\n            ',(null as any));
    this._text_108 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_109 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_110 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','clearfix form-footer'),(null as any));
    this._text_111 = this.renderer.createText(this._el_110,'\n        ',(null as any));
    this._el_112 = import3.createRenderElement(this.renderer,this._el_110,'button',new import3.InlineArray4(4,'class','zui-btn zui-btn-sec','type','button'),(null as any));
    this._text_113 = this.renderer.createText(this._el_112,'Cancel',(null as any));
    this._text_114 = this.renderer.createText(this._el_110,'\n          ',(null as any));
    this._el_115 = import3.createRenderElement(this.renderer,this._el_110,'button',new import3.InlineArray4(4,'class','zui-btn zui-btn-primary','type','submit'),(null as any));
    this._text_116 = this.renderer.createText(this._el_115,'',(null as any));
    this._text_117 = this.renderer.createText(this._el_110,'\n\n        ',(null as any));
    this._text_118 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_119 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_120 = import3.createRenderElement(this.renderer,this._el_0,'zui-form-dirty-dialog',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_120 = new import32.View_FormDirtyDialogComponent0(this.viewUtils,this,120,this._el_120);
    this._FormDirtyDialogComponent_120_3 = new import32.Wrapper_FormDirtyDialogComponent();
    this._text_121 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_120.create(this._FormDirtyDialogComponent_120_3.context);
    this._text_122 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_123 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_124 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_124 = new import12.ViewContainer(124,0,this,this._anchor_124);
    this._TemplateRef_124_5 = new import20.TemplateRef_(this,124,this._anchor_124);
    this._NgIf_124_6 = new import19.Wrapper_NgIf(this._vc_124.vcRef,this._TemplateRef_124_5);
    this._text_125 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_126 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_9));
    this._FormGroupDirective_9_3.subscribe(this,this.eventHandler(this.handleEvent_9),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_23));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_31,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_31));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_52,new import3.InlineArray4(4,'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_52));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_70,new import3.InlineArray4(4,'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_70));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_91,new import3.InlineArray2(2,'validateDate',(null as any)),this.eventHandler(this.handleEvent_91));
    this._CalendarComponent_91_3.subscribe(this,this.eventHandler(this.handleEvent_91),true);
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_103,new import3.InlineArray2(2,'validateDate',(null as any)),this.eventHandler(this.handleEvent_103));
    this._CalendarComponent_103_3.subscribe(this,this.eventHandler(this.handleEvent_103),true);
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_112,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_112));
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_120,new import3.InlineArray4(4,'dismissNavigation',(null as any),'continueNavigation',(null as any)),this.eventHandler(this.handleEvent_120));
    this._FormDirtyDialogComponent_120_3.subscribe(this,this.eventHandler(this.handleEvent_120),true,true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._anchor_40,
      this._text_41,
      this._anchor_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._anchor_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._text_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._text_106,
      this._text_107,
      this._text_108,
      this._text_109,
      this._el_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._text_117,
      this._text_118,
      this._text_119,
      this._el_120,
      this._text_121,
      this._text_122,
      this._text_123,
      this._anchor_124,
      this._text_125,
      this._text_126
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import21.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import20.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import21.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6.context; }
    if (((token === import34.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3.context; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_4; }
    if (((token === import36.FormControlName) && (23 === requestNodeIndex))) { return this._FormControlName_23_5.context; }
    if (((token === import37.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_6; }
    if (((token === import38.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_7.context; }
    if (((token === import34.DefaultValueAccessor) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._DefaultValueAccessor_31_3.context; }
    if (((token === import35.NG_VALUE_ACCESSOR) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NG_VALUE_ACCESSOR_31_4; }
    if (((token === import36.FormControlName) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._FormControlName_31_5.context; }
    if (((token === import37.NgControl) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgControl_31_6; }
    if (((token === import38.NgControlStatus) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgControlStatus_31_7.context; }
    if (((token === import20.TemplateRef) && (40 === requestNodeIndex))) { return this._TemplateRef_40_5; }
    if (((token === import21.NgIf) && (40 === requestNodeIndex))) { return this._NgIf_40_6.context; }
    if (((token === import20.TemplateRef) && (42 === requestNodeIndex))) { return this._TemplateRef_42_5; }
    if (((token === import21.NgIf) && (42 === requestNodeIndex))) { return this._NgIf_42_6.context; }
    if (((token === import39.CheckboxControlValueAccessor) && (52 === requestNodeIndex))) { return this._CheckboxControlValueAccessor_52_3.context; }
    if (((token === import35.NG_VALUE_ACCESSOR) && (52 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_52_4; }
    if (((token === import36.FormControlName) && (52 === requestNodeIndex))) { return this._FormControlName_52_5.context; }
    if (((token === import37.NgControl) && (52 === requestNodeIndex))) { return this._NgControl_52_6; }
    if (((token === import38.NgControlStatus) && (52 === requestNodeIndex))) { return this._NgControlStatus_52_7.context; }
    if (((token === import17.NgSelectOption) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._NgSelectOption_72_3.context; }
    if (((token === import18.NgSelectMultipleOption) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._NgSelectMultipleOption_72_4.context; }
    if (((token === import20.TemplateRef) && (75 === requestNodeIndex))) { return this._TemplateRef_75_5; }
    if (((token === import40.NgFor) && (75 === requestNodeIndex))) { return this._NgFor_75_6.context; }
    if (((token === import17.SelectControlValueAccessor) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._SelectControlValueAccessor_70_3.context; }
    if (((token === import35.NG_VALUE_ACCESSOR) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._NG_VALUE_ACCESSOR_70_4; }
    if (((token === import41.FormControlDirective) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._FormControlDirective_70_5.context; }
    if (((token === import37.NgControl) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._NgControl_70_6; }
    if (((token === import38.NgControlStatus) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._NgControlStatus_70_7.context; }
    if (((token === import29.CalendarComponent) && ((91 <= requestNodeIndex) && (requestNodeIndex <= 92)))) { return this._CalendarComponent_91_3.context; }
    if (((token === import29.CalendarComponent) && ((103 <= requestNodeIndex) && (requestNodeIndex <= 104)))) { return this._CalendarComponent_103_3.context; }
    if (((token === import42.FormGroupDirective) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 118)))) { return this._FormGroupDirective_9_3.context; }
    if (((token === import43.ControlContainer) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 118)))) { return this._ControlContainer_9_4; }
    if (((token === import38.NgControlStatusGroup) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 118)))) { return this._NgControlStatusGroup_9_5.context; }
    if (((token === import31.FormDirtyDialogComponent) && ((120 <= requestNodeIndex) && (requestNodeIndex <= 121)))) { return this._FormDirtyDialogComponent_120_3.context; }
    if (((token === import20.TemplateRef) && (124 === requestNodeIndex))) { return this._TemplateRef_124_5; }
    if (((token === import21.NgIf) && (124 === requestNodeIndex))) { return this._NgIf_124_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4_0_0:boolean = !this.context.isAdd;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    const currVal_6_0_0:any = this.context.isAdd;
    this._NgIf_6_6.check_ngIf(currVal_6_0_0,throwOnChange,false);
    this._NgIf_6_6.ngDoCheck(this,this._anchor_6,throwOnChange);
    const currVal_9_0_0:any = this.context.releaseForm;
    this._FormGroupDirective_9_3.check_form(currVal_9_0_0,throwOnChange,false);
    this._FormGroupDirective_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    this._NgControlStatusGroup_9_5.ngDoCheck(this,this._el_9,throwOnChange);
    this._DefaultValueAccessor_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_1_0:any = 'name';
    this._FormControlName_23_5.check_name(currVal_23_1_0,throwOnChange,false);
    this._FormControlName_23_5.ngDoCheck(this,this._el_23,throwOnChange);
    this._NgControlStatus_23_7.ngDoCheck(this,this._el_23,throwOnChange);
    this._DefaultValueAccessor_31_3.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_31_1_0:any = 'description';
    this._FormControlName_31_5.check_name(currVal_31_1_0,throwOnChange,false);
    this._FormControlName_31_5.ngDoCheck(this,this._el_31,throwOnChange);
    this._NgControlStatus_31_7.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_40_0_0:any = this.context.isAdd;
    this._NgIf_40_6.check_ngIf(currVal_40_0_0,throwOnChange,false);
    this._NgIf_40_6.ngDoCheck(this,this._anchor_40,throwOnChange);
    const currVal_42_0_0:boolean = !this.context.isAdd;
    this._NgIf_42_6.check_ngIf(currVal_42_0_0,throwOnChange,false);
    this._NgIf_42_6.ngDoCheck(this,this._anchor_42,throwOnChange);
    this._CheckboxControlValueAccessor_52_3.ngDoCheck(this,this._el_52,throwOnChange);
    const currVal_52_1_0:any = 'status';
    this._FormControlName_52_5.check_name(currVal_52_1_0,throwOnChange,false);
    this._FormControlName_52_5.ngDoCheck(this,this._el_52,throwOnChange);
    this._NgControlStatus_52_7.ngDoCheck(this,this._el_52,throwOnChange);
    this._SelectControlValueAccessor_70_3.ngDoCheck(this,this._el_70,throwOnChange);
    const currVal_70_1_0:any = this.context.releaseForm.controls['externalSystem'];
    this._FormControlDirective_70_5.check_form(currVal_70_1_0,throwOnChange,false);
    this._FormControlDirective_70_5.ngDoCheck(this,this._el_70,throwOnChange);
    this._NgControlStatus_70_7.ngDoCheck(this,this._el_70,throwOnChange);
    this._NgSelectOption_72_3.ngDoCheck(this,this._el_72,throwOnChange);
    this._NgSelectMultipleOption_72_4.ngDoCheck(this,this._el_72,throwOnChange);
    const currVal_75_0_0:any = this.context.defectProjects;
    this._NgFor_75_6.check_ngForOf(currVal_75_0_0,throwOnChange,false);
    this._NgFor_75_6.ngDoCheck(this,this._anchor_75,throwOnChange);
    const currVal_91_0_0:any = this.context.releaseForm.controls['startDate'];
    this._CalendarComponent_91_3.check_formkey(currVal_91_0_0,throwOnChange,false);
    const currVal_91_0_1:any = this.context.release.startDate;
    this._CalendarComponent_91_3.check_model(currVal_91_0_1,throwOnChange,false);
    const currVal_91_0_2:any = this.context.datesValidation.startDateMin;
    this._CalendarComponent_91_3.check_minDate(currVal_91_0_2,throwOnChange,false);
    const currVal_91_0_3:any = this.context.datesValidation.startDateMax;
    this._CalendarComponent_91_3.check_maxDate(currVal_91_0_3,throwOnChange,false);
    this._CalendarComponent_91_3.ngDoCheck(this,this._el_91,throwOnChange);
    const currVal_103_0_0:any = this.context.releaseForm.controls['endDate'];
    this._CalendarComponent_103_3.check_formkey(currVal_103_0_0,throwOnChange,false);
    const currVal_103_0_1:any = this.context.release.endDate;
    this._CalendarComponent_103_3.check_model(currVal_103_0_1,throwOnChange,false);
    const currVal_103_0_2:any = this.context.datesValidation.endDateMin;
    this._CalendarComponent_103_3.check_minDate(currVal_103_0_2,throwOnChange,false);
    const currVal_103_0_3:any = this.context.datesValidation.endDateMax;
    this._CalendarComponent_103_3.check_maxDate(currVal_103_0_3,throwOnChange,false);
    this._CalendarComponent_103_3.ngDoCheck(this,this._el_103,throwOnChange);
    const currVal_120_0_0:any = this.context.showDirtyCheckModal;
    this._FormDirtyDialogComponent_120_3.check_show(currVal_120_0_0,throwOnChange,false);
    this._FormDirtyDialogComponent_120_3.ngDoCheck(this,this._el_120,throwOnChange);
    const currVal_124_0_0:any = this.context.confirmationObject;
    this._NgIf_124_6.check_ngIf(currVal_124_0_0,throwOnChange,false);
    this._NgIf_124_6.ngDoCheck(this,this._anchor_124,throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
    this._vc_40.detectChangesInNestedViews(throwOnChange);
    this._vc_42.detectChangesInNestedViews(throwOnChange);
    this._vc_75.detectChangesInNestedViews(throwOnChange);
    this._vc_124.detectChangesInNestedViews(throwOnChange);
    const currVal_176:boolean = !this.context.isShowForm;
    if (import3.checkBinding(throwOnChange,this._expr_176,currVal_176)) {
      this.renderer.setElementProperty(this._el_0,'hidden',currVal_176);
      this._expr_176 = currVal_176;
    }
    this._NgControlStatusGroup_9_5.checkHost(this,this,this._el_9,throwOnChange);
    this._NgControlStatus_23_7.checkHost(this,this,this._el_23,throwOnChange);
    this._NgControlStatus_31_7.checkHost(this,this,this._el_31,throwOnChange);
    this._NgControlStatus_52_7.checkHost(this,this,this._el_52,throwOnChange);
    const currVal_177:boolean = !this.context.isDefectOn;
    if (import3.checkBinding(throwOnChange,this._expr_177,currVal_177)) {
      this.renderer.setElementProperty(this._el_61,'hidden',currVal_177);
      this._expr_177 = currVal_177;
    }
    this._NgControlStatus_70_7.checkHost(this,this,this._el_70,throwOnChange);
    const currVal_178:any = '';
    if (import3.checkBinding(throwOnChange,this._expr_178,currVal_178)) {
      this.renderer.setElementAttribute(this._el_72,'value',((currVal_178 == null)? (null as any): currVal_178.toString()));
      this._expr_178 = currVal_178;
    }
    const currVal_179:any = this.context.isFormInValid(this.context.releaseForm);
    if (import3.checkBinding(throwOnChange,this._expr_179,currVal_179)) {
      this.renderer.setElementProperty(this._el_115,'disabled',currVal_179);
      this._expr_179 = currVal_179;
    }
    const currVal_180:any = import3.inlineInterpolate(1,' ',(this.context.isAdd? 'Add': 'Save'),'');
    if (import3.checkBinding(throwOnChange,this._expr_180,currVal_180)) {
      this.renderer.setText(this._text_116,currVal_180);
      this._expr_180 = currVal_180;
    }
    this.compView_91.internalDetectChanges(throwOnChange);
    this.compView_103.internalDetectChanges(throwOnChange);
    this.compView_120.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._CalendarComponent_91_3.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._CalendarComponent_103_3.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._vc_4.destroyNestedViews();
    this._vc_6.destroyNestedViews();
    this._vc_40.destroyNestedViews();
    this._vc_42.destroyNestedViews();
    this._vc_75.destroyNestedViews();
    this._vc_124.destroyNestedViews();
    this.compView_91.destroy();
    this.compView_103.destroy();
    this.compView_120.destroy();
    this._FormControlName_23_5.ngOnDestroy();
    this._FormControlName_31_5.ngOnDestroy();
    this._FormControlName_52_5.ngOnDestroy();
    this._NgSelectOption_72_3.ngOnDestroy();
    this._NgSelectMultipleOption_72_4.ngOnDestroy();
    this._FormControlDirective_70_5.ngOnDestroy();
    this._CalendarComponent_91_3.ngOnDestroy();
    this._CalendarComponent_103_3.ngOnDestroy();
    this._FormGroupDirective_9_3.ngOnDestroy();
    this._FormDirtyDialogComponent_120_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 4)) { return new View_ReleaseFormComponent1(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    if ((nodeIndex == 6)) { return new View_ReleaseFormComponent2(this.viewUtils,this,6,this._anchor_6,this._vc_6); }
    if ((nodeIndex == 40)) { return new View_ReleaseFormComponent3(this.viewUtils,this,40,this._anchor_40,this._vc_40); }
    if ((nodeIndex == 42)) { return new View_ReleaseFormComponent4(this.viewUtils,this,42,this._anchor_42,this._vc_42); }
    if ((nodeIndex == 75)) { return new View_ReleaseFormComponent5(this.viewUtils,this,75,this._anchor_75,this._vc_75); }
    if ((nodeIndex == 124)) { return new View_ReleaseFormComponent6(this.viewUtils,this,124,this._anchor_124,this._vc_124); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_9_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.onReleaseFormSubmit(this.context.releaseForm.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_23_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_31(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_31_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_52(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._CheckboxControlValueAccessor_52_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'change')) {
      const pd_sub_0:any = ((<any>this.context.onChangeHide($event.target.checked)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_70(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_70_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_91(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'validateDate')) {
      const pd_sub_0:any = ((<any>this.context.onChangeStartDate($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_103(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'validateDate')) {
      const pd_sub_0:any = ((<any>this.context.onChangeEndDate($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_112(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.cancelReleaseForm()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_120(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'dismissNavigation')) {
      const pd_sub_0:any = ((<any>this.context.dismissNavigation($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'continueNavigation')) {
      const pd_sub_1:any = ((<any>this.context.continueNavigation($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}