/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../app/view/components/reports/TCEPPhase.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from 'ng2-nvd3/build/lib/ng2-nvd3.component';
import * as import9 from '../../../../node_modules/ng2-nvd3/build/lib/ng2-nvd3.component.ngfactory';
import * as import10 from '../../../../../app/view/components/grid/grid.component';
import * as import11 from '../../../../../app/actions/grid.action';
import * as import12 from '../../../../../app/actions/global.action';
import * as import13 from '../../../../../app/utils/scripts/utils';
import * as import14 from '../grid/grid.component.ngfactory';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/http/src/http';
import * as import17 from '../../../../../app/services/pouch.db.service';
import * as import18 from '@angular/core/src/zone/ng_zone';
import * as import19 from '@angular/router/src/router';
import * as import20 from '../../../../../app/services/toastr.service';
export class Wrapper_TCEPPhaseComponent {
  /*private*/ _eventHandler:Function;
  context:import0.TCEPPhaseComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.TCEPPhaseComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_TCEPPhaseComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_TCEPPhaseComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.TCEPPhaseComponent>;
  _TCEPPhaseComponent_0_3:Wrapper_TCEPPhaseComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TCEPPhaseComponent_Host0,renderType_TCEPPhaseComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'TCEPPhase',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TCEPPhaseComponent0(this.viewUtils,this,0,this._el_0);
    this._TCEPPhaseComponent_0_3 = new Wrapper_TCEPPhaseComponent();
    this.compView_0.create(this._TCEPPhaseComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._TCEPPhaseComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TCEPPhaseComponent) && (0 === requestNodeIndex))) { return this._TCEPPhaseComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TCEPPhaseComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TCEPPhaseComponentNgFactory:import7.ComponentFactory<import0.TCEPPhaseComponent> = new import7.ComponentFactory<import0.TCEPPhaseComponent>('TCEPPhase',View_TCEPPhaseComponent_Host0,import0.TCEPPhaseComponent);
const styles_TCEPPhaseComponent:any[] = ([] as any[]);
var renderType_TCEPPhaseComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_TCEPPhaseComponent,{});
export class View_TCEPPhaseComponent0 extends import1.AppView<import0.TCEPPhaseComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  compView_13:import1.AppView<import8.NvD3Component>;
  _NvD3Component_13_3:import9.Wrapper_NvD3Component;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _el_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _el_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _el_99:any;
  _text_100:any;
  _el_101:any;
  compView_101:import1.AppView<import10.GridComponent>;
  _GridAction_101_3:import11.GridAction;
  _GlobalAction_101_4:import12.GlobalAction;
  _UtililtyFunctions_101_5:import13.UtililtyFunctions;
  _GridComponent_101_6:import14.Wrapper_GridComponent;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TCEPPhaseComponent0,renderType_TCEPPhaseComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'section',new import3.InlineArray4(4,'class','reports-content','role','main'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Test Case Execution Progress Cycle \\  Test Case Execution Progress Phase',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n\n  ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','col-md-8'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'nvd3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_13 = new import9.View_NvD3Component0(this.viewUtils,this,13,this._el_13);
    this._NvD3Component_13_3 = new import9.Wrapper_NvD3Component(new import15.ElementRef(this._el_13));
    this.compView_13.create(this._NvD3Component_13_3.context);
    this._text_14 = this.renderer.createText(this._el_11,'\n\n  ',(null as any));
    this._text_15 = this.renderer.createText(this._el_9,'\n  ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','col-md-4'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Summary',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_16,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'LastUpdated: Aug 1, 2017 04:19:47 PM',(null as any));
    this._text_23 = this.renderer.createText(this._el_16,'\n\n',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_16,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Maura ZP',(null as any));
    this._text_26 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_16,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Release 1.0',(null as any));
    this._text_29 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_16,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','summary-wrapper'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'table',new import3.InlineArray2(2,'class','tcep-summary'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n  ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_34,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n    ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_38,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Total # of Cycles:',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_38,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'8',(null as any));
    this._text_43 = this.renderer.createText(this._el_36,'\n      ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_36,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_44,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'Total Scheduled:',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_44,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'8',(null as any));
    this._text_49 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_36,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_50,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'Total Executed:',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_50,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'8',(null as any));
    this._text_55 = this.renderer.createText(this._el_36,'\n          ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_36,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_56,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'% Executed:',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_56,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'8',(null as any));
    this._text_61 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_36,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_62,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'Total Blocked:',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_62,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'8',(null as any));
    this._text_67 = this.renderer.createText(this._el_36,'\n              ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_36,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_68,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'Total Fail:',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_68,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'8',(null as any));
    this._text_73 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_36,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_74,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'Total Invalid:',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_74,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'8',(null as any));
    this._text_79 = this.renderer.createText(this._el_36,'\n                  ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_36,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_80,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'Total N/A:',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_80,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'8',(null as any));
    this._text_85 = this.renderer.createText(this._el_36,'\n                    ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_36,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_87 = import3.createRenderElement(this.renderer,this._el_86,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_88 = this.renderer.createText(this._el_87,'Total Pass:',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_86,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'8',(null as any));
    this._text_91 = this.renderer.createText(this._el_36,'\n  ',(null as any));
    this._text_92 = this.renderer.createText(this._el_34,'\n',(null as any));
    this._text_93 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._text_94 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_95 = this.renderer.createText(this._el_9,'\n',(null as any));
    this._text_96 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'\n  ',(null as any));
    this._el_99 = import3.createRenderElement(this.renderer,this._el_97,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_100 = this.renderer.createText(this._el_99,'\n    ',(null as any));
    this._el_101 = import3.createRenderElement(this.renderer,this._el_99,'grid',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_101 = new import14.View_GridComponent0(this.viewUtils,this,101,this._el_101);
    this._GridAction_101_3 = new import11.GridAction(this.parentView.injectorGet(import16.Http,this.parentIndex),this.parentView.injectorGet(import17.PouchDBPrefsServices,this.parentIndex));
    this._GlobalAction_101_4 = new import12.GlobalAction(this.parentView.injectorGet(import16.Http,this.parentIndex));
    this._UtililtyFunctions_101_5 = new import13.UtililtyFunctions();
    this._GridComponent_101_6 = new import14.Wrapper_GridComponent(this._GridAction_101_3,this._GlobalAction_101_4,new import15.ElementRef(this._el_101),this._UtililtyFunctions_101_5,this.compView_101.ref,this.parentView.injectorGet(import18.NgZone,this.parentIndex),this.parentView.injectorGet(import19.Router,this.parentIndex),this.parentView.injectorGet(import17.PouchDBPrefsServices,this.parentIndex),this.parentView.injectorGet(import20.ToastrService,this.parentIndex));
    this.compView_101.create(this._GridComponent_101_6.context);
    this._text_102 = this.renderer.createText(this._el_99,'\n  ',(null as any));
    this._text_103 = this.renderer.createText(this._el_97,'\n',(null as any));
    this._text_104 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_105 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._text_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._text_105
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.NvD3Component) && (13 === requestNodeIndex))) { return this._NvD3Component_13_3.context; }
    if (((token === import11.GridAction) && (101 === requestNodeIndex))) { return this._GridAction_101_3; }
    if (((token === import12.GlobalAction) && (101 === requestNodeIndex))) { return this._GlobalAction_101_4; }
    if (((token === import13.UtililtyFunctions) && (101 === requestNodeIndex))) { return this._UtililtyFunctions_101_5; }
    if (((token === import10.GridComponent) && (101 === requestNodeIndex))) { return this._GridComponent_101_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_13_0_0:any = this.context.options;
    this._NvD3Component_13_3.check_options(currVal_13_0_0,throwOnChange,false);
    const currVal_13_0_1:any = this.context.data;
    this._NvD3Component_13_3.check_data(currVal_13_0_1,throwOnChange,false);
    this._NvD3Component_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_101_0_0:any = this.context.gridData;
    this._GridComponent_101_6.check_rows(currVal_101_0_0,throwOnChange,false);
    this._GridComponent_101_6.ngDoCheck(this,this._el_101,throwOnChange);
    this.compView_13.internalDetectChanges(throwOnChange);
    this.compView_101.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._GridComponent_101_6.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_13.destroy();
    this.compView_101.destroy();
    this._NvD3Component_13_3.ngOnDestroy();
    this._GridComponent_101_6.ngOnDestroy();
  }
}