/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../app/view/components/dashboard/dashboards.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../../../../app/actions/dashboard.action';
import * as import6 from '../../../../../app/actions/grid.action';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/constants';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/router/src/router';
import * as import12 from '../../../../../app/services/pouch.db.service';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/forms/src/form_builder';
import * as import15 from '../../../../../app/services/toastr.service';
import * as import16 from '../../../../../app/view/components/dashboard/dashboard_form/dashboard_form.component';
import * as import17 from './dashboard_form/dashboard_form.component.ngfactory';
import * as import18 from '@angular/core/src/linker/view_container';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from '../../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import21 from '../../../../../app/view/components/grid/grid.component';
import * as import22 from '../../../../../app/actions/global.action';
import * as import23 from '../../../../../app/utils/scripts/utils';
import * as import24 from '../grid/grid.component.ngfactory';
import * as import25 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import26 from '../../../../../app/view/components/common/modal/modal.component';
import * as import27 from '../common/modal/modal.component.ngfactory';
import * as import28 from '../../../../../app/view/components/form_dirty_dialog/form_dirty_dialog.component';
import * as import29 from '../form_dirty_dialog/form_dirty_dialog.component.ngfactory';
import * as import30 from '@angular/common/src/pipes/i18n_select_pipe';
import * as import31 from '@angular/core/src/change_detection/change_detection_util';
import * as import32 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import33 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import34 from '@angular/core/src/linker/element_ref';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from '@angular/core/src/linker/template_ref';
import * as import37 from '@angular/common/src/directives/ng_class';
import * as import38 from '@angular/common/src/directives/ng_if';
export class Wrapper_DashboardsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.DashboardsComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this._changed = false;
    this.context = new import0.DashboardsComponent(p0,p1,p2,p3,p4,p5);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_DashboardsComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_DashboardsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.DashboardsComponent>;
  _DashboardAction_0_3:import5.DashboardAction;
  _GridAction_0_4:import6.GridAction;
  _DashboardsComponent_0_5:Wrapper_DashboardsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DashboardsComponent_Host0,renderType_DashboardsComponent_Host,import7.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'zui-dashboard',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_DashboardsComponent0(this.viewUtils,this,0,this._el_0);
    this._DashboardAction_0_3 = new import5.DashboardAction(this.injectorGet(import10.Http,this.parentIndex),this.injectorGet(import11.Router,this.parentIndex));
    this._GridAction_0_4 = new import6.GridAction(this.injectorGet(import10.Http,this.parentIndex),this.injectorGet(import12.PouchDBPrefsServices,this.parentIndex));
    this._DashboardsComponent_0_5 = new Wrapper_DashboardsComponent(this._DashboardAction_0_3,this._GridAction_0_4,this.injectorGet(import11.Router,this.parentIndex),this.injectorGet(import13.ActivatedRoute,this.parentIndex),this.injectorGet(import14.FormBuilder,this.parentIndex),this.injectorGet(import15.ToastrService,this.parentIndex));
    this.compView_0.create(this._DashboardsComponent_0_5.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._DashboardsComponent_0_5.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.DashboardAction) && (0 === requestNodeIndex))) { return this._DashboardAction_0_3; }
    if (((token === import6.GridAction) && (0 === requestNodeIndex))) { return this._GridAction_0_4; }
    if (((token === import0.DashboardsComponent) && (0 === requestNodeIndex))) { return this._DashboardsComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DashboardsComponent_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._DashboardsComponent_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const DashboardsComponentNgFactory:import9.ComponentFactory<import0.DashboardsComponent> = new import9.ComponentFactory<import0.DashboardsComponent>('zui-dashboard',View_DashboardsComponent_Host0,import0.DashboardsComponent);
const styles_DashboardsComponent:any[] = ([] as any[]);
class View_DashboardsComponent1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import16.DashboardFormComponent>;
  _DashboardAction_0_3:import5.DashboardAction;
  _GridAction_0_4:import6.GridAction;
  _DashboardFormComponent_0_5:import17.Wrapper_DashboardFormComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import18.ViewContainer) {
    super(View_DashboardsComponent1,renderType_DashboardsComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'dashboard-form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import17.View_DashboardFormComponent0(this.viewUtils,this,0,this._el_0);
    this._DashboardAction_0_3 = new import5.DashboardAction(this.parentView.parentView.injectorGet(import10.Http,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import11.Router,this.parentView.parentIndex));
    this._GridAction_0_4 = new import6.GridAction(this.parentView.parentView.injectorGet(import10.Http,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import12.PouchDBPrefsServices,this.parentView.parentIndex));
    this._DashboardFormComponent_0_5 = new import17.Wrapper_DashboardFormComponent(this._DashboardAction_0_3,this._GridAction_0_4,this.parentView.parentView.injectorGet(import11.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import14.FormBuilder,this.parentView.parentIndex));
    this.compView_0.create(this._DashboardFormComponent_0_5.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'onCancel',(null as any)),this.eventHandler(this.handleEvent_0));
    this._DashboardFormComponent_0_5.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.DashboardAction) && (0 === requestNodeIndex))) { return this._DashboardAction_0_3; }
    if (((token === import6.GridAction) && (0 === requestNodeIndex))) { return this._GridAction_0_4; }
    if (((token === import16.DashboardFormComponent) && (0 === requestNodeIndex))) { return this._DashboardFormComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context._dashboard;
    this._DashboardFormComponent_0_5.check_dashboard(currVal_0_0_0,throwOnChange,false);
    this._DashboardFormComponent_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<View_DashboardsComponent0>this.parentView)._viewQuery_DashboardFormComponent_0.setDirty();
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._DashboardFormComponent_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onCancel')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onClickClearDashboardState()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_DashboardsComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_DashboardsComponent,{});
export class View_DashboardsComponent0 extends import1.AppView<import0.DashboardsComponent> {
  _viewQuery_DashboardFormComponent_0:import19.QueryList<any>;
  _viewQuery_GridComponent_1:import19.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _NgClass_45_3:import20.Wrapper_NgClass;
  _text_46:any;
  _el_47:any;
  compView_47:import1.AppView<import21.GridComponent>;
  _GridAction_47_3:import6.GridAction;
  _GlobalAction_47_4:import22.GlobalAction;
  _UtililtyFunctions_47_5:import23.UtililtyFunctions;
  _GridComponent_47_6:import24.Wrapper_GridComponent;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _anchor_66:any;
  /*private*/ _vc_66:import18.ViewContainer;
  _TemplateRef_66_5:any;
  _NgIf_66_6:import25.Wrapper_NgIf;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  compView_70:import1.AppView<import26.ModalComponent>;
  _ModalComponent_70_3:import27.Wrapper_ModalComponent;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  compView_88:import1.AppView<import28.FormDirtyDialogComponent>;
  _FormDirtyDialogComponent_88_3:import29.Wrapper_FormDirtyDialogComponent;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  /*private*/ _expr_111:any;
  /*private*/ _expr_112:any;
  /*private*/ _expr_113:any;
  _pipe_i18nSelect_0:import30.I18nSelectPipe;
  _pipe_i18nSelect_0_0:any;
  _map_116:any;
  _pipe_i18nSelect_0_1:any;
  /*private*/ _expr_118:any;
  _pipe_i18nSelect_0_2:any;
  _pipe_i18nSelect_0_3:any;
  /*private*/ _expr_121:any;
  _pipe_i18nSelect_0_4:any;
  /*private*/ _expr_123:any;
  _pipe_i18nSelect_0_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DashboardsComponent0,renderType_DashboardsComponent,import7.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways);
    this._expr_111 = import31.UNINITIALIZED;
    this._expr_112 = import31.UNINITIALIZED;
    this._expr_113 = import31.UNINITIALIZED;
    this._map_116 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {'pref-selected': p0};
    });
    this._expr_118 = import31.UNINITIALIZED;
    this._expr_121 = import31.UNINITIALIZED;
    this._expr_123 = import31.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_DashboardFormComponent_0 = new import19.QueryList<any>();
    this._viewQuery_GridComponent_1 = new import19.QueryList<any>();
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','main-content clearfix'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','flex','style','padding-bottom: 1rem'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h1',new import3.InlineArray2(2,'style','margin: 0'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','right-navs'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','zui-input-group project-search'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n          ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'input',new import3.InlineArray8(6,'class','form-control','placeholder','Search for...','type','text'),(null as any));
    this._text_17 = this.renderer.createText(this._el_14,'\n          ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_14,'span',new import3.InlineArray2(2,'class','input-group-btn'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n		            ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'button',new import3.InlineArray4(4,'class','zui-btn zui-btn-primary cursor-pointer','type','button'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n		        	    ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'span',new import3.InlineArray2(2,'class','fa fa-search'),(null as any));
    this._text_23 = this.renderer.createText(this._el_20,'\n		        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_18,'\n		      ',(null as any));
    this._text_25 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._text_26 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_12,'button',new import3.InlineArray4(4,'class','zui-btn zui-btn-plus dashboard-add','title','Add Dashboard'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'+',(null as any));
    this._text_29 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._text_30 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','zui-content-layout release-setup-container flex-column-stretch','style','background: #fff;'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n      ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray8(6,'class','tab-pane fade in active','id','preference','role','tabpanel'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_36 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_37 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_39 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_42 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_43 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_34,'div',new import3.InlineArray2(2,'class','col-md-12 dashboards-grid'),(null as any));
    this._NgClass_45_3 = new import20.Wrapper_NgClass(this.parentView.injectorGet(import32.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import33.KeyValueDiffers,this.parentIndex),new import34.ElementRef(this._el_45),this.renderer);
    this._text_46 = this.renderer.createText(this._el_45,'\n          ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_45,'grid',new import3.InlineArray2(2,'class','dashboard-new-grid-table'),(null as any));
    this.compView_47 = new import24.View_GridComponent0(this.viewUtils,this,47,this._el_47);
    this._GridAction_47_3 = new import6.GridAction(this.parentView.injectorGet(import10.Http,this.parentIndex),this.parentView.injectorGet(import12.PouchDBPrefsServices,this.parentIndex));
    this._GlobalAction_47_4 = new import22.GlobalAction(this.parentView.injectorGet(import10.Http,this.parentIndex));
    this._UtililtyFunctions_47_5 = new import23.UtililtyFunctions();
    this._GridComponent_47_6 = new import24.Wrapper_GridComponent(this._GridAction_47_3,this._GlobalAction_47_4,new import34.ElementRef(this._el_47),this._UtililtyFunctions_47_5,this.compView_47.ref,this.parentView.injectorGet(import35.NgZone,this.parentIndex),this.parentView.injectorGet(import11.Router,this.parentIndex),this.parentView.injectorGet(import12.PouchDBPrefsServices,this.parentIndex),this.parentView.injectorGet(import15.ToastrService,this.parentIndex));
    this._text_48 = this.renderer.createText((null as any),'\n          ',(null as any));
    this.compView_47.create(this._GridComponent_47_6.context);
    this._text_49 = this.renderer.createText(this._el_45,'\n          ',(null as any));
    this._text_50 = this.renderer.createText(this._el_45,'\n          ',(null as any));
    this._text_51 = this.renderer.createText(this._el_45,'\n        ',(null as any));
    this._text_52 = this.renderer.createText(this._el_34,'\n\n\n\n        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_55 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_56 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_57 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_58 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_59 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_60 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_62 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_63 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_64 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_65 = this.renderer.createText(this._el_34,'\n\n        ',(null as any));
    this._anchor_66 = this.renderer.createTemplateAnchor(this._el_34,(null as any));
    this._vc_66 = new import18.ViewContainer(66,34,this,this._anchor_66);
    this._TemplateRef_66_5 = new import36.TemplateRef_(this,66,this._anchor_66);
    this._NgIf_66_6 = new import25.Wrapper_NgIf(this._vc_66.vcRef,this._TemplateRef_66_5);
    this._text_67 = this.renderer.createText(this._el_34,'\n      ',(null as any));
    this._text_68 = this.renderer.createText(this._el_32,'\n\n      ',(null as any));
    this._text_69 = this.renderer.createText(this._el_32,'\n      ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_32,'zui-modal',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_70 = new import27.View_ModalComponent0(this.viewUtils,this,70,this._el_70);
    this._ModalComponent_70_3 = new import27.Wrapper_ModalComponent(new import34.ElementRef(this._el_70),this.compView_70.ref);
    this._text_71 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,(null as any),'zui-modal-body',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n          ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_72,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'',(null as any));
    this._text_76 = this.renderer.createText(this._el_72,'\n        ',(null as any));
    this._text_77 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_78 = import3.createRenderElement(this.renderer,(null as any),'zui-modal-footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_79 = this.renderer.createText(this._el_78,'\n          ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_78,'button',new import3.InlineArray8(6,'class','zui-btn zui-btn-sec','data-dismiss','modal','type','button'),(null as any));
    this._text_81 = this.renderer.createText(this._el_80,'',(null as any));
    this._text_82 = this.renderer.createText(this._el_78,'\n          ',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_78,'button',new import3.InlineArray4(4,'class','zui-btn zui-btn-primary','type','button'),(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'',(null as any));
    this._text_85 = this.renderer.createText(this._el_78,'\n\n        ',(null as any));
    this._text_86 = this.renderer.createText((null as any),'\n      ',(null as any));
    this.compView_70.create(this._ModalComponent_70_3.context);
    this._text_87 = this.renderer.createText(this._el_32,'\n\n      ',(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_32,'zui-form-dirty-dialog',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_88 = new import29.View_FormDirtyDialogComponent0(this.viewUtils,this,88,this._el_88);
    this._FormDirtyDialogComponent_88_3 = new import29.Wrapper_FormDirtyDialogComponent();
    this.compView_88.create(this._FormDirtyDialogComponent_88_3.context);
    this._text_89 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._text_90 = this.renderer.createText(this._el_2,'\n\n\n    ',(null as any));
    this._text_91 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_92 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_93 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_94 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_95 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._pipe_i18nSelect_0 = new import30.I18nSelectPipe();
    this._pipe_i18nSelect_0_0 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray2(2,'keyup',(null as any)),this.eventHandler(this.handleEvent_16));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_20));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_27,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_27));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_47,new import3.InlineArray16(12,'onGridActionIconClick',(null as any),'onGridPaginateByIndex',(null as any),'onGridPageSizeChange',(null as any),'onGridRowClick',(null as any),'onGridPrevClick',(null as any),'onGridNextClick',(null as any)),this.eventHandler(this.handleEvent_47));
    this._GridComponent_47_6.subscribe(this,this.eventHandler(this.handleEvent_47),false,true,true,false,false,true,false,true,false,true,true,false,false,false,false,false,false);
    this._pipe_i18nSelect_0_1 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    this._pipe_i18nSelect_0_2 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    this._pipe_i18nSelect_0_3 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_80,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_80));
    this._pipe_i18nSelect_0_4 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_83,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_83));
    this._pipe_i18nSelect_0_5 = import3.pureProxy2(this._pipe_i18nSelect_0.transform.bind(this._pipe_i18nSelect_0));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_88,new import3.InlineArray4(4,'dismissNavigation',(null as any),'continueNavigation',(null as any)),this.eventHandler(this.handleEvent_88));
    this._FormDirtyDialogComponent_88_3.subscribe(this,this.eventHandler(this.handleEvent_88),true,true);
    this._viewQuery_GridComponent_1.reset([this._GridComponent_47_6.context]);
    this.context.gridComponent = this._viewQuery_GridComponent_1.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._anchor_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._text_94,
      this._text_95
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import6.GridAction) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._GridAction_47_3; }
    if (((token === import22.GlobalAction) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._GlobalAction_47_4; }
    if (((token === import23.UtililtyFunctions) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._UtililtyFunctions_47_5; }
    if (((token === import21.GridComponent) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._GridComponent_47_6.context; }
    if (((token === import37.NgClass) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._NgClass_45_3.context; }
    if (((token === import36.TemplateRef) && (66 === requestNodeIndex))) { return this._TemplateRef_66_5; }
    if (((token === import38.NgIf) && (66 === requestNodeIndex))) { return this._NgIf_66_6.context; }
    if (((token === import26.ModalComponent) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._ModalComponent_70_3.context; }
    if (((token === import28.FormDirtyDialogComponent) && (88 === requestNodeIndex))) { return this._FormDirtyDialogComponent_88_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import31.ValueUnwrapper();
    const currVal_45_0_0:any = 'col-md-12 dashboards-grid';
    this._NgClass_45_3.check_klass(currVal_45_0_0,throwOnChange,false);
    const currVal_45_0_1:any = this._map_116(this.context.selectedCategory);
    this._NgClass_45_3.check_ngClass(currVal_45_0_1,throwOnChange,false);
    this._NgClass_45_3.ngDoCheck(this,this._el_45,throwOnChange);
    const currVal_47_0_0:any = this.context._rows;
    this._GridComponent_47_6.check_rows(currVal_47_0_0,throwOnChange,false);
    const currVal_47_0_1:any = this.context._dashboardGridType;
    this._GridComponent_47_6.check_gridType(currVal_47_0_1,throwOnChange,false);
    const currVal_47_0_2:any = this.context.paginationOptions;
    this._GridComponent_47_6.check_paginationOptions(currVal_47_0_2,throwOnChange,false);
    this._GridComponent_47_6.ngDoCheck(this,this._el_47,throwOnChange);
    const currVal_66_0_0:any = this.context._dashboard;
    this._NgIf_66_6.check_ngIf(currVal_66_0_0,throwOnChange,false);
    this._NgIf_66_6.ngDoCheck(this,this._anchor_66,throwOnChange);
    valUnwrapper.reset();
    const currVal_70_0_0:any = valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_1,this._pipe_i18nSelect_0.transform)('zephyr.dashboard.delete.title',this.context.i18nMessages));
    this._ModalComponent_70_3.check_title(currVal_70_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    const currVal_70_0_1:any = 'zui-dashboard-modal-delete';
    this._ModalComponent_70_3.check_modalId(currVal_70_0_1,throwOnChange,false);
    const currVal_70_0_2:any = 'medium';
    this._ModalComponent_70_3.check_modalSize(currVal_70_0_2,throwOnChange,false);
    this._ModalComponent_70_3.ngDoCheck(this,this._el_70,throwOnChange);
    const currVal_88_0_0:any = this.context.showDirtyCheckModal;
    this._FormDirtyDialogComponent_88_3.check_show(currVal_88_0_0,throwOnChange,false);
    this._FormDirtyDialogComponent_88_3.ngDoCheck(this,this._el_88,throwOnChange);
    this._vc_66.detectChangesInNestedViews(throwOnChange);
    const currVal_111:any = 'zee-layout zui-dashboard-container';
    if (import3.checkBinding(throwOnChange,this._expr_111,currVal_111)) {
      this.renderer.setElementProperty(this._el_0,'className',currVal_111);
      this._expr_111 = currVal_111;
    }
    const currVal_112:any = 'component-heading zee-content-title';
    if (import3.checkBinding(throwOnChange,this._expr_112,currVal_112)) {
      this.renderer.setElementProperty(this._el_8,'className',currVal_112);
      this._expr_112 = currVal_112;
    }
    valUnwrapper.reset();
    const currVal_113:any = import3.inlineInterpolate(1,'\n          ',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_0,this._pipe_i18nSelect_0.transform)('zephyr.dashboard.label',this.context.i18nMessages)),'\n        ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_113,currVal_113))) {
      this.renderer.setText(this._text_9,currVal_113);
      this._expr_113 = currVal_113;
    }
    valUnwrapper.reset();
    const currVal_118:any = import3.inlineInterpolate(3,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_2,this._pipe_i18nSelect_0.transform)('zephyr.dashboard.delete.prefix',this.context.i18nMessages)),' ',((this.context.dashboardToBeDeleted == null)? (null as any): this.context.dashboardToBeDeleted.name),' ',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_3,this._pipe_i18nSelect_0.transform)('zephyr.dashboard.delete.suffix',this.context.i18nMessages)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_118,currVal_118))) {
      this.renderer.setText(this._text_75,currVal_118);
      this._expr_118 = currVal_118;
    }
    valUnwrapper.reset();
    const currVal_121:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_4,this._pipe_i18nSelect_0.transform)('zephyr.button.cancel',this.context.i18nMessages)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_121,currVal_121))) {
      this.renderer.setText(this._text_81,currVal_121);
      this._expr_121 = currVal_121;
    }
    valUnwrapper.reset();
    const currVal_123:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_i18nSelect_0_5,this._pipe_i18nSelect_0.transform)('zephyr.button.delete',this.context.i18nMessages)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_123,currVal_123))) {
      this.renderer.setText(this._text_84,currVal_123);
      this._expr_123 = currVal_123;
    }
    this.compView_47.internalDetectChanges(throwOnChange);
    this.compView_70.internalDetectChanges(throwOnChange);
    this.compView_88.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._viewQuery_DashboardFormComponent_0.dirty) {
          this._viewQuery_DashboardFormComponent_0.reset([this._vc_66.mapNestedViews(View_DashboardsComponent1,(nestedView:View_DashboardsComponent1):any => {
            return [nestedView._DashboardFormComponent_0_5.context];
        })]);
        this.context.dashboardForm = this._viewQuery_DashboardFormComponent_0.first;
      }
      if ((this.numberOfChecks === 0)) { this._GridComponent_47_6.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._ModalComponent_70_3.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._vc_66.destroyNestedViews();
    this.compView_47.destroy();
    this.compView_70.destroy();
    this.compView_88.destroy();
    this._GridComponent_47_6.ngOnDestroy();
    this._ModalComponent_70_3.ngOnDestroy();
    this._FormDirtyDialogComponent_88_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 70) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 70) && (ngContentIndex == 1))) { cb(this._el_72,ctx); }
    if (((nodeIndex == 70) && (ngContentIndex == 2))) { cb(this._el_78,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 66)) { return new View_DashboardsComponent1(this.viewUtils,this,66,this._anchor_66,this._vc_66); }
    return (null as any);
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'keyup')) {
      const pd_sub_0:any = ((<any>this.context.inputSearchKeyPress($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickSearch()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_27(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickCreateDashboard()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_47(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onGridActionIconClick')) {
      const pd_sub_0:any = ((<any>this.context.dashboardGridIconClick($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onGridPaginateByIndex')) {
      const pd_sub_1:any = ((<any>this.context.dashboardGridPaginate($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'onGridPageSizeChange')) {
      const pd_sub_2:any = ((<any>this.context.dashboardGridPageSizeChange($event)) !== false);
      result = (pd_sub_2 && result);
    }
    if ((eventName == 'onGridRowClick')) {
      const pd_sub_3:any = ((<any>this.context.dashboardGridRowClick($event)) !== false);
      result = (pd_sub_3 && result);
    }
    if ((eventName == 'onGridPrevClick')) {
      const pd_sub_4:any = ((<any>this.context.dashboardGridPrevClick($event)) !== false);
      result = (pd_sub_4 && result);
    }
    if ((eventName == 'onGridNextClick')) {
      const pd_sub_5:any = ((<any>this.context.dashboardGridNextClick($event)) !== false);
      result = (pd_sub_5 && result);
    }
    return result;
  }
  handleEvent_80(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickClearDashboardState()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_83(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickDeleteDashboard()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_88(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'dismissNavigation')) {
      const pd_sub_0:any = ((<any>this.context.dismissNavigation($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'continueNavigation')) {
      const pd_sub_1:any = ((<any>this.context.continueNavigation($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}