/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../../../app/view/components/defects/defect_link/create_defect/fields/cd_optionwithchild.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '../../../../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import11 from '../../../../../../../../app/view/components/common/select/select.component';
import * as import12 from '../../../../common/select/select.component.ngfactory';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/common/src/directives/ng_if';
export class Wrapper_CDOptionWithChildComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CDOptionWithChildComponent;
  /*private*/ _changed:boolean;
  /*private*/ _changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  subscription0:any;
  constructor() {
    this._changed = false;
    this._changes = {};
    this.context = new import0.CDOptionWithChildComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_field(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.field = currValue;
      this._changes['field'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  check_formkey(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.formkey = currValue;
      this._changes['formkey'] = new import1.SimpleChange(this._expr_1,currValue);
      this._expr_1 = currValue;
    }
  }
  check_projectkey(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.projectkey = currValue;
      this._changes['projectkey'] = new import1.SimpleChange(this._expr_2,currValue);
      this._expr_2 = currValue;
    }
  }
  check_isUpdate(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.isUpdate = currValue;
      this._changes['isUpdate'] = new import1.SimpleChange(this._expr_3,currValue);
      this._expr_3 = currValue;
    }
  }
  check_casCadeSelectDefault(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_4,currValue))) {
      this._changed = true;
      this.context.casCadeSelectDefault = currValue;
      this._changes['casCadeSelectDefault'] = new import1.SimpleChange(this._expr_4,currValue);
      this._expr_4 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) {
      if (changed) {
        this.context.ngOnChanges(this._changes);
        this._changes = {};
      }
      if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); }
    }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.optionChange.subscribe(_eventHandler.bind(view,'optionChange'))); }
  }
}
var renderType_CDOptionWithChildComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_CDOptionWithChildComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.CDOptionWithChildComponent>;
  _CDOptionWithChildComponent_0_3:Wrapper_CDOptionWithChildComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CDOptionWithChildComponent_Host0,renderType_CDOptionWithChildComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'cd-optionwithchild',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CDOptionWithChildComponent0(this.viewUtils,this,0,this._el_0);
    this._CDOptionWithChildComponent_0_3 = new Wrapper_CDOptionWithChildComponent();
    this.compView_0.create(this._CDOptionWithChildComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._CDOptionWithChildComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CDOptionWithChildComponent) && (0 === requestNodeIndex))) { return this._CDOptionWithChildComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._CDOptionWithChildComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._CDOptionWithChildComponent_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CDOptionWithChildComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CDOptionWithChildComponentNgFactory:import8.ComponentFactory<import0.CDOptionWithChildComponent> = new import8.ComponentFactory<import0.CDOptionWithChildComponent>('cd-optionwithchild',View_CDOptionWithChildComponent_Host0,import0.CDOptionWithChildComponent);
const styles_CDOptionWithChildComponent:any[] = ([] as any[]);
class View_CDOptionWithChildComponent1 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_CDOptionWithChildComponent1,renderType_CDOptionWithChildComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'label',new import3.InlineArray2(2,'class','required'),(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,' *',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_CDOptionWithChildComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_CDOptionWithChildComponent,{});
export class View_CDOptionWithChildComponent0 extends import2.AppView<import0.CDOptionWithChildComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import9.ViewContainer;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import10.Wrapper_NgIf;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  compView_13:import2.AppView<import11.SelectComponent>;
  _SelectComponent_13_3:import12.Wrapper_SelectComponent;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  compView_19:import2.AppView<import11.SelectComponent>;
  _SelectComponent_19_3:import12.Wrapper_SelectComponent;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  /*private*/ _expr_31:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CDOptionWithChildComponent0,renderType_CDOptionWithChildComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckOnce);
    this._expr_31 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-2'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_4,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_8 = new import9.ViewContainer(8,2,this,this._anchor_8);
    this._TemplateRef_8_5 = new import13.TemplateRef_(this,8,this._anchor_8);
    this._NgIf_8_6 = new import10.Wrapper_NgIf(this._vc_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_2,' :\n  ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray2(2,'class','col-md-4'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n              ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'zee-select',new import3.InlineArray2(2,'class','zui-cascade-select1'),(null as any));
    this.compView_13 = new import12.View_SelectComponent0(this.viewUtils,this,13,this._el_13);
    this._SelectComponent_13_3 = new import12.Wrapper_SelectComponent(new import14.ElementRef(this._el_13));
    this._text_14 = this.renderer.createText((null as any),'\n              ',(null as any));
    this.compView_13.create(this._SelectComponent_13_3.context);
    this._text_15 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray2(2,'class','col-md-4'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n              ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'zee-select',new import3.InlineArray2(2,'class','zui-cascade-select2'),(null as any));
    this.compView_19 = new import12.View_SelectComponent0(this.viewUtils,this,19,this._el_19);
    this._SelectComponent_19_3 = new import12.Wrapper_SelectComponent(new import14.ElementRef(this._el_19));
    this._text_20 = this.renderer.createText((null as any),'\n              ',(null as any));
    this.compView_19.create(this._SelectComponent_19_3.context);
    this._text_21 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_13,new import3.InlineArray2(2,'onSelect',(null as any)),this.eventHandler(this.handleEvent_13));
    this._SelectComponent_13_3.subscribe(this,this.eventHandler(this.handleEvent_13),true,false,false,false);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray2(2,'onSelect',(null as any)),this.eventHandler(this.handleEvent_19));
    this._SelectComponent_19_3.subscribe(this,this.eventHandler(this.handleEvent_19),true,false,false,false);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import15.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6.context; }
    if (((token === import11.SelectComponent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._SelectComponent_13_3.context; }
    if (((token === import11.SelectComponent) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._SelectComponent_19_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_8_0_0:any = this.context.field.required;
    this._NgIf_8_6.check_ngIf(currVal_8_0_0,throwOnChange,false);
    this._NgIf_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    const currVal_13_0_0:any = (this.context.field.fieldKey + '-field');
    this._SelectComponent_13_3.check_selectId(currVal_13_0_0,throwOnChange,false);
    const currVal_13_0_1:any = this.context.fieldoption1;
    this._SelectComponent_13_3.check_items(currVal_13_0_1,throwOnChange,false);
    const currVal_13_0_2:any = 'Select a value';
    this._SelectComponent_13_3.check_placeholder(currVal_13_0_2,throwOnChange,false);
    this._SelectComponent_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_19_0_0:any = (this.context.field.fieldKey + '-field-child');
    this._SelectComponent_19_3.check_selectId(currVal_19_0_0,throwOnChange,false);
    const currVal_19_0_1:any = this.context.fieldoption2;
    this._SelectComponent_19_3.check_items(currVal_19_0_1,throwOnChange,false);
    const currVal_19_0_2:any = 'Select a value';
    this._SelectComponent_19_3.check_placeholder(currVal_19_0_2,throwOnChange,false);
    this._SelectComponent_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    const currVal_31:any = import3.inlineInterpolate(1,'',this.context.field.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setText(this._text_6,currVal_31);
      this._expr_31 = currVal_31;
    }
    this.compView_13.internalDetectChanges(throwOnChange);
    this.compView_19.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._SelectComponent_13_3.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._SelectComponent_19_3.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._vc_8.destroyNestedViews();
    this.compView_13.destroy();
    this.compView_19.destroy();
    this._SelectComponent_13_3.ngOnDestroy();
    this._SelectComponent_19_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 8)) { return new View_CDOptionWithChildComponent1(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    return (null as any);
  }
  handleEvent_13(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSelect')) {
      const pd_sub_0:any = ((<any>this.context.onChangeAppOptions($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSelect')) {
      const pd_sub_0:any = ((<any>this.context.onChangeReleaseOption($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}