/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../app/view/components/projects/project_details.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '../../../../../app/actions/release.action';
import * as import7 from '../../../../../app/actions/project.action';
import * as import8 from '../../../../../app/actions/notification.action';
import * as import9 from '@angular/core/src/linker/view_type';
import * as import10 from '@angular/core/src/change_detection/constants';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/http/src/http';
import * as import13 from '../../../../../app/actions/admin.action';
import * as import14 from '@angular/router/src/router';
import * as import15 from '../../../../../app/services/zephyr.event.service';
import * as import16 from '@angular/router/src/router_state';
import * as import17 from '@angular/core/src/linker/view_container';
import * as import18 from '../../../../../app/view/components/common/modules/module1';
import * as import19 from '../common/modules/module1.ngfactory';
import * as import20 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import21 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import22 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import23 from '../../../../../app/view/components/common/select/select.component';
import * as import24 from '../common/select/select.component.ngfactory';
import * as import25 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import26 from '@angular/core/src/linker/template_ref';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import29 from '@angular/common/src/directives/ng_if';
import * as import30 from '@angular/forms/src/directives/ng_form';
import * as import31 from '@angular/forms/src/directives/control_container';
import * as import32 from '@angular/forms/src/directives/ng_control_status';
import * as import33 from '@angular/common/src/directives/ng_for';
export class Wrapper_ProjectDetailsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ProjectDetailsComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this._changed = false;
    this.context = new import0.ProjectDetailsComponent(p0,p1,p2,p3,p4,p5);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  check_appId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.appId = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ProjectDetailsComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_ProjectDetailsComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.ProjectDetailsComponent>;
  _ReleaseAction_0_3:import6.ReleaseAction;
  _ProjectAction_0_4:import7.ProjectAction;
  _NotificationAction_0_5:import8.NotificationAction;
  _ProjectDetailsComponent_0_6:Wrapper_ProjectDetailsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ProjectDetailsComponent_Host0,renderType_ProjectDetailsComponent_Host,import9.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import11.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'project-details',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ProjectDetailsComponent0(this.viewUtils,this,0,this._el_0);
    this._ReleaseAction_0_3 = new import6.ReleaseAction(this.injectorGet(import12.Http,this.parentIndex));
    this._ProjectAction_0_4 = new import7.ProjectAction(this.injectorGet(import12.Http,this.parentIndex),this.injectorGet(import13.AdminAction,this.parentIndex),this._ReleaseAction_0_3);
    this._NotificationAction_0_5 = new import8.NotificationAction(this.injectorGet(import12.Http,this.parentIndex));
    this._ProjectDetailsComponent_0_6 = new Wrapper_ProjectDetailsComponent(this._ProjectAction_0_4,this.injectorGet(import14.Router,this.parentIndex),this._ReleaseAction_0_3,this._NotificationAction_0_5,this.injectorGet(import15.ZephyrEventService,this.parentIndex),this.injectorGet(import16.ActivatedRoute,this.parentIndex));
    this.compView_0.create(this._ProjectDetailsComponent_0_6.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import11.ComponentRef_<any>(0,this,this._el_0,this._ProjectDetailsComponent_0_6.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import6.ReleaseAction) && (0 === requestNodeIndex))) { return this._ReleaseAction_0_3; }
    if (((token === import7.ProjectAction) && (0 === requestNodeIndex))) { return this._ProjectAction_0_4; }
    if (((token === import8.NotificationAction) && (0 === requestNodeIndex))) { return this._NotificationAction_0_5; }
    if (((token === import0.ProjectDetailsComponent) && (0 === requestNodeIndex))) { return this._ProjectDetailsComponent_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ProjectDetailsComponent_0_6.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._ProjectDetailsComponent_0_6.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._ProjectDetailsComponent_0_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ProjectDetailsComponentNgFactory:import11.ComponentFactory<import0.ProjectDetailsComponent> = new import11.ComponentFactory<import0.ProjectDetailsComponent>('project-details',View_ProjectDetailsComponent_Host0,import0.ProjectDetailsComponent);
const styles_ProjectDetailsComponent:any[] = ([] as any[]);
class View_ProjectDetailsComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_ProjectDetailsComponent1,renderType_ProjectDetailsComponent,import9.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import10.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_8 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import11.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-12 zephyr-project-details'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'p',new import3.InlineArray2(2,'class','zephyr-content-subtitle'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_8:any = import3.inlineInterpolate(1,'',this.parentView.context.project.description,'');
    if (import3.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_5,currVal_8);
      this._expr_8 = currVal_8;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ProjectDetailsComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import18.ContentModule1Component>;
  _ContentModule1Component_2_3:import19.Wrapper_ContentModule1Component;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_ProjectDetailsComponent2,renderType_ProjectDetailsComponent,import9.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import10.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import11.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','zui-project-summary-wrapper'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'zui-summary-box',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import19.View_ContentModule1Component0(this.viewUtils,this,2,this._el_2);
    this._ContentModule1Component_2_3 = new import19.Wrapper_ContentModule1Component();
    this.compView_2.create(this._ContentModule1Component_2_3.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.ContentModule1Component) && (2 === requestNodeIndex))) { return this._ContentModule1Component_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.$implicit;
    this._ContentModule1Component_2_3.check_summary(currVal_2_0_0,throwOnChange,false);
    this._ContentModule1Component_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_ProjectDetailsComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_ProjectDetailsComponent,{});
export class View_ProjectDetailsComponent0 extends import2.AppView<import0.ProjectDetailsComponent> {
  _text_0:any;
  _anchor_1:any;
  /*private*/ _vc_1:import17.ViewContainer;
  _TemplateRef_1_5:any;
  _NgIf_1_6:import20.Wrapper_NgIf;
  _text_2:any;
  _el_3:any;
  _NgForm_3_3:import21.Wrapper_NgForm;
  _ControlContainer_3_4:any;
  _NgControlStatusGroup_3_5:import22.Wrapper_NgControlStatusGroup;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  compView_7:import2.AppView<import23.SelectComponent>;
  _SelectComponent_7_3:import24.Wrapper_SelectComponent;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _vc_17:import17.ViewContainer;
  _TemplateRef_17_5:any;
  _NgFor_17_6:import25.Wrapper_NgFor;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  /*private*/ _expr_32:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ProjectDetailsComponent0,renderType_ProjectDetailsComponent,import9.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import10.ChangeDetectorStatus.CheckAlways);
    this._expr_32 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import11.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_1 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_1 = new import17.ViewContainer(1,(null as any),this,this._anchor_1);
    this._TemplateRef_1_5 = new import26.TemplateRef_(this,1,this._anchor_1);
    this._NgIf_1_6 = new import20.Wrapper_NgIf(this._vc_1.vcRef,this._TemplateRef_1_5);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_3_3 = new import21.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_3_4 = this._NgForm_3_3.context;
    this._NgControlStatusGroup_3_5 = new import22.Wrapper_NgControlStatusGroup(this._ControlContainer_3_4);
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','zui-ng-select project-release-select'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'zee-select',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_7 = new import24.View_SelectComponent0(this.viewUtils,this,7,this._el_7);
    this._SelectComponent_7_3 = new import24.Wrapper_SelectComponent(new import27.ElementRef(this._el_7));
    this.compView_7.create(this._SelectComponent_7_3.context);
    this._text_8 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','zui-project-summary-container'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_17 = new import17.ViewContainer(17,15,this,this._anchor_17);
    this._TemplateRef_17_5 = new import26.TemplateRef_(this,17,this._anchor_17);
    this._NgFor_17_6 = new import25.Wrapper_NgFor(this._vc_17.vcRef,this._TemplateRef_17_5,this.parentView.injectorGet(import28.IterableDiffers,this.parentIndex),this.ref);
    this._text_18 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n',(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_3,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_3));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'onSelect',(null as any)),this.eventHandler(this.handleEvent_7));
    this._SelectComponent_7_3.subscribe(this,this.eventHandler(this.handleEvent_7),true,false,false,false);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._anchor_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._text_19,
      this._text_20
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_5; }
    if (((token === import29.NgIf) && (1 === requestNodeIndex))) { return this._NgIf_1_6.context; }
    if (((token === import23.SelectComponent) && (7 === requestNodeIndex))) { return this._SelectComponent_7_3.context; }
    if (((token === import30.NgForm) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NgForm_3_3.context; }
    if (((token === import31.ControlContainer) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ControlContainer_3_4; }
    if (((token === import32.NgControlStatusGroup) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NgControlStatusGroup_3_5.context; }
    if (((token === import26.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import33.NgFor) && (17 === requestNodeIndex))) { return this._NgFor_17_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = ((this.context.project == null)? (null as any): this.context.project.description);
    this._NgIf_1_6.check_ngIf(currVal_1_0_0,throwOnChange,false);
    this._NgIf_1_6.ngDoCheck(this,this._anchor_1,throwOnChange);
    this._NgForm_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    this._NgControlStatusGroup_3_5.ngDoCheck(this,this._el_3,throwOnChange);
    const currVal_7_0_0:any = true;
    this._SelectComponent_7_3.check_allowClear(currVal_7_0_0,throwOnChange,false);
    const currVal_7_0_1:any = this.context.releases;
    this._SelectComponent_7_3.check_items(currVal_7_0_1,throwOnChange,false);
    const currVal_7_0_2:any = 'Go to Release';
    this._SelectComponent_7_3.check_placeholder(currVal_7_0_2,throwOnChange,false);
    const currVal_7_0_3:any = false;
    this._SelectComponent_7_3.check_hideSearch(currVal_7_0_3,throwOnChange,false);
    this._SelectComponent_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    const currVal_17_0_0:any = this.context.summaries;
    this._NgFor_17_6.check_ngForOf(currVal_17_0_0,throwOnChange,false);
    this._NgFor_17_6.ngDoCheck(this,this._anchor_17,throwOnChange);
    this._vc_1.detectChangesInNestedViews(throwOnChange);
    this._vc_17.detectChangesInNestedViews(throwOnChange);
    const currVal_32:any = '';
    if (import3.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementProperty(this._el_3,'className',currVal_32);
      this._expr_32 = currVal_32;
    }
    this._NgControlStatusGroup_3_5.checkHost(this,this,this._el_3,throwOnChange);
    this.compView_7.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._SelectComponent_7_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._vc_1.destroyNestedViews();
    this._vc_17.destroyNestedViews();
    this.compView_7.destroy();
    this._SelectComponent_7_3.ngOnDestroy();
    this._NgForm_3_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 1)) { return new View_ProjectDetailsComponent1(this.viewUtils,this,1,this._anchor_1,this._vc_1); }
    if ((nodeIndex == 17)) { return new View_ProjectDetailsComponent2(this.viewUtils,this,17,this._anchor_17,this._vc_17); }
    return (null as any);
  }
  handleEvent_3(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_3_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSelect')) {
      const pd_sub_0:any = ((<any>this.context.goToRelease($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}