/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../app/view/components/testcase/testcase_details.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../../../app/actions/testcase.action';
import * as import10 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/core/src/security';
import * as import13 from '../../../../../app/view/components/inline_edit/inline_edit.component';
import * as import14 from '../../../../../app/utils/scripts/utils';
import * as import15 from '../inline_edit/inline_edit.component.ngfactory';
import * as import16 from '@angular/forms/src/form_builder';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '../../directives/expander/expander.directive.ngfactory';
import * as import19 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import20 from '../../../../../app/view/pipes/grid_actions.pipe';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@angular/common/src/directives/ng_if';
import * as import23 from '../../../../../app/view/directives/expander/expander.directive';
export class Wrapper_TestcaseDetailsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.TestcaseDetailsComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  subscription0:any;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.TestcaseDetailsComponent(p0,p1);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_editable(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.editable = currValue;
      this._expr_0 = currValue;
    }
  }
  check_allowRequirementMapping(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.allowRequirementMapping = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.updateTestCase.subscribe(_eventHandler.bind(view,'updateTestCase'))); }
  }
}
var renderType_TestcaseDetailsComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_TestcaseDetailsComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.TestcaseDetailsComponent>;
  _TestcaseDetailsComponent_0_3:Wrapper_TestcaseDetailsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TestcaseDetailsComponent_Host0,renderType_TestcaseDetailsComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'zee-panel-content2',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TestcaseDetailsComponent0(this.viewUtils,this,0,this._el_0);
    this._TestcaseDetailsComponent_0_3 = new Wrapper_TestcaseDetailsComponent(this.injectorGet(import9.TestcaseAction,this.parentIndex),this.injectorGet(import10.DomSanitizer,this.parentIndex));
    this.compView_0.create(this._TestcaseDetailsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._TestcaseDetailsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TestcaseDetailsComponent) && (0 === requestNodeIndex))) { return this._TestcaseDetailsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TestcaseDetailsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._TestcaseDetailsComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TestcaseDetailsComponentNgFactory:import8.ComponentFactory<import0.TestcaseDetailsComponent> = new import8.ComponentFactory<import0.TestcaseDetailsComponent>('zee-panel-content2',View_TestcaseDetailsComponent_Host0,import0.TestcaseDetailsComponent);
const styles_TestcaseDetailsComponent:any[] = ([] as any[]);
class View_TestcaseDetailsComponent1 extends import2.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  _map_2:any;
  _arr_3:any;
  _pipe_gridActionsPipe_0_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_TestcaseDetailsComponent1,renderType_TestcaseDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import1.UNINITIALIZED;
    this._map_2 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {key: p0};
    });
    this._arr_3 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._pipe_gridActionsPipe_0_0 = import3.pureProxy2((<View_TestcaseDetailsComponent0>this.parentView)._pipe_gridActionsPipe_0.transform.bind((<View_TestcaseDetailsComponent0>this.parentView)._pipe_gridActionsPipe_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_1:any = valUnwrapper.unwrap(import3.castByValue(this._pipe_gridActionsPipe_0_0,(<View_TestcaseDetailsComponent0>this.parentView)._pipe_gridActionsPipe_0.transform)(this.parentView.context.testcase.priority,this._arr_3(this._map_2('testcasePriority'))));
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this.renderer.setElementProperty(this._el_0,'innerHTML',this.viewUtils.sanitizer.sanitize(import12.SecurityContext.HTML,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_TestcaseDetailsComponent2 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import13.InlineEditComponent>;
  _UtililtyFunctions_0_3:import14.UtililtyFunctions;
  _InlineEditComponent_0_4:import15.Wrapper_InlineEditComponent;
  _map_4:any;
  _arr_5:any;
  _pipe_gridActionsPipe_0_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_TestcaseDetailsComponent2,renderType_TestcaseDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._map_4 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {key: p0};
    });
    this._arr_5 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'zephyr-inline-edit',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import15.View_InlineEditComponent0(this.viewUtils,this,0,this._el_0);
    this._UtililtyFunctions_0_3 = new import14.UtililtyFunctions();
    this._InlineEditComponent_0_4 = new import15.Wrapper_InlineEditComponent(this.parentView.parentView.injectorGet(import16.FormBuilder,this.parentView.parentIndex),new import17.ElementRef(this._el_0),this.compView_0.ref,this._UtililtyFunctions_0_3);
    this.compView_0.create(this._InlineEditComponent_0_4.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'onSubmit',(null as any)),this.eventHandler(this.handleEvent_0));
    this._InlineEditComponent_0_4.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this._pipe_gridActionsPipe_0_1 = import3.pureProxy2((<View_TestcaseDetailsComponent0>this.parentView)._pipe_gridActionsPipe_0.transform.bind((<View_TestcaseDetailsComponent0>this.parentView)._pipe_gridActionsPipe_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.UtililtyFunctions) && (0 === requestNodeIndex))) { return this._UtililtyFunctions_0_3; }
    if (((token === import13.InlineEditComponent) && (0 === requestNodeIndex))) { return this._InlineEditComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_0_0_0:any = valUnwrapper.unwrap(import3.castByValue(this._pipe_gridActionsPipe_0_1,(<View_TestcaseDetailsComponent0>this.parentView)._pipe_gridActionsPipe_0.transform)(this.parentView.context.testcase.priority,this._arr_5(this._map_4('testcasePriority'))));
    this._InlineEditComponent_0_4.check_field(currVal_0_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    const currVal_0_0_1:any = 'singleselect';
    this._InlineEditComponent_0_4.check_editType(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = this.parentView.context.testcase.priorities;
    this._InlineEditComponent_0_4.check_fieldOptions(currVal_0_0_2,throwOnChange,false);
    const currVal_0_0_3:any = this.parentView.context.testcase.priority;
    this._InlineEditComponent_0_4.check_selectedOption(currVal_0_0_3,throwOnChange,false);
    const currVal_0_0_4:any = 'Enter priority';
    this._InlineEditComponent_0_4.check_placeholder(currVal_0_0_4,throwOnChange,false);
    const currVal_0_0_5:any = this.parentView.context.getSelect2Options('priority');
    this._InlineEditComponent_0_4.check_editOptions(currVal_0_0_5,throwOnChange,false);
    if (this._InlineEditComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._InlineEditComponent_0_4.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._InlineEditComponent_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.savePriority($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_TestcaseDetailsComponent3 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_TestcaseDetailsComponent3,renderType_TestcaseDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.context.testcase.externalId,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_TestcaseDetailsComponent4 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import13.InlineEditComponent>;
  _UtililtyFunctions_0_3:import14.UtililtyFunctions;
  _InlineEditComponent_0_4:import15.Wrapper_InlineEditComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_TestcaseDetailsComponent4,renderType_TestcaseDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'zephyr-inline-edit',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import15.View_InlineEditComponent0(this.viewUtils,this,0,this._el_0);
    this._UtililtyFunctions_0_3 = new import14.UtililtyFunctions();
    this._InlineEditComponent_0_4 = new import15.Wrapper_InlineEditComponent(this.parentView.parentView.injectorGet(import16.FormBuilder,this.parentView.parentIndex),new import17.ElementRef(this._el_0),this.compView_0.ref,this._UtililtyFunctions_0_3);
    this.compView_0.create(this._InlineEditComponent_0_4.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'onSubmit',(null as any)),this.eventHandler(this.handleEvent_0));
    this._InlineEditComponent_0_4.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.UtililtyFunctions) && (0 === requestNodeIndex))) { return this._UtililtyFunctions_0_3; }
    if (((token === import13.InlineEditComponent) && (0 === requestNodeIndex))) { return this._InlineEditComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.testcase.externalId;
    this._InlineEditComponent_0_4.check_field(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = 'text';
    this._InlineEditComponent_0_4.check_editType(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = 'Enter alt ID';
    this._InlineEditComponent_0_4.check_placeholder(currVal_0_0_2,throwOnChange,false);
    const currVal_0_0_3:any = this.parentView.context.altIdValidation;
    this._InlineEditComponent_0_4.check_validationPattern(currVal_0_0_3,throwOnChange,false);
    const currVal_0_0_4:any = 255;
    this._InlineEditComponent_0_4.check_maxCount(currVal_0_0_4,throwOnChange,false);
    if (this._InlineEditComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._InlineEditComponent_0_4.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._InlineEditComponent_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.saveExternalId($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_TestcaseDetailsComponent5 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_TestcaseDetailsComponent5,renderType_TestcaseDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.context.testcase.tags,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_TestcaseDetailsComponent6 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import13.InlineEditComponent>;
  _UtililtyFunctions_0_3:import14.UtililtyFunctions;
  _InlineEditComponent_0_4:import15.Wrapper_InlineEditComponent;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_TestcaseDetailsComponent6,renderType_TestcaseDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'zephyr-inline-edit',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import15.View_InlineEditComponent0(this.viewUtils,this,0,this._el_0);
    this._UtililtyFunctions_0_3 = new import14.UtililtyFunctions();
    this._InlineEditComponent_0_4 = new import15.Wrapper_InlineEditComponent(this.parentView.parentView.injectorGet(import16.FormBuilder,this.parentView.parentIndex),new import17.ElementRef(this._el_0),this.compView_0.ref,this._UtililtyFunctions_0_3);
    this.compView_0.create(this._InlineEditComponent_0_4.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'onSubmit',(null as any)),this.eventHandler(this.handleEvent_0));
    this._InlineEditComponent_0_4.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.UtililtyFunctions) && (0 === requestNodeIndex))) { return this._UtililtyFunctions_0_3; }
    if (((token === import13.InlineEditComponent) && (0 === requestNodeIndex))) { return this._InlineEditComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.testcase.tags;
    this._InlineEditComponent_0_4.check_field(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = 'multiselect-ajax';
    this._InlineEditComponent_0_4.check_editType(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = this.parentView.context.testcase.tagOptions;
    this._InlineEditComponent_0_4.check_fieldOptions(currVal_0_0_2,throwOnChange,false);
    const currVal_0_0_3:any = this.parentView.context.testcase.tags;
    this._InlineEditComponent_0_4.check_selectedOption(currVal_0_0_3,throwOnChange,false);
    const currVal_0_0_4:any = 'Enter tags';
    this._InlineEditComponent_0_4.check_placeholder(currVal_0_0_4,throwOnChange,false);
    const currVal_0_0_5:any = this.parentView.context.getSelect2Options('tags');
    this._InlineEditComponent_0_4.check_editOptions(currVal_0_0_5,throwOnChange,false);
    const currVal_0_0_6:any = true;
    this._InlineEditComponent_0_4.check_saveOnEnter(currVal_0_0_6,throwOnChange,false);
    const currVal_0_0_7:any = true;
    this._InlineEditComponent_0_4.check_tags(currVal_0_0_7,throwOnChange,false);
    if (this._InlineEditComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    const currVal_4:any = true;
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_0,'multiple',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._InlineEditComponent_0_4.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._InlineEditComponent_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.saveTags($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_TestcaseDetailsComponent7 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_TestcaseDetailsComponent7,renderType_TestcaseDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.context.testcase.comments,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_TestcaseDetailsComponent8 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import13.InlineEditComponent>;
  _UtililtyFunctions_0_3:import14.UtililtyFunctions;
  _InlineEditComponent_0_4:import15.Wrapper_InlineEditComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_TestcaseDetailsComponent8,renderType_TestcaseDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'zephyr-inline-edit',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import15.View_InlineEditComponent0(this.viewUtils,this,0,this._el_0);
    this._UtililtyFunctions_0_3 = new import14.UtililtyFunctions();
    this._InlineEditComponent_0_4 = new import15.Wrapper_InlineEditComponent(this.parentView.parentView.injectorGet(import16.FormBuilder,this.parentView.parentIndex),new import17.ElementRef(this._el_0),this.compView_0.ref,this._UtililtyFunctions_0_3);
    this.compView_0.create(this._InlineEditComponent_0_4.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'onSubmit',(null as any)),this.eventHandler(this.handleEvent_0));
    this._InlineEditComponent_0_4.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.UtililtyFunctions) && (0 === requestNodeIndex))) { return this._UtililtyFunctions_0_3; }
    if (((token === import13.InlineEditComponent) && (0 === requestNodeIndex))) { return this._InlineEditComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.testcase.comments;
    this._InlineEditComponent_0_4.check_field(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = 'textarea';
    this._InlineEditComponent_0_4.check_editType(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = 'Enter comment';
    this._InlineEditComponent_0_4.check_placeholder(currVal_0_0_2,throwOnChange,false);
    const currVal_0_0_3:any = this.parentView.context.commentsValidation;
    this._InlineEditComponent_0_4.check_validationPattern(currVal_0_0_3,throwOnChange,false);
    const currVal_0_0_4:any = 2048;
    this._InlineEditComponent_0_4.check_maxCount(currVal_0_0_4,throwOnChange,false);
    if (this._InlineEditComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._InlineEditComponent_0_4.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._InlineEditComponent_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.saveComment($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_TestcaseDetailsComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_TestcaseDetailsComponent,{});
export class View_TestcaseDetailsComponent0 extends import2.AppView<import0.TestcaseDetailsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _ExpanderDirective_2_3:import18.Wrapper_ExpanderDirective;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _anchor_40:any;
  /*private*/ _vc_40:import11.ViewContainer;
  _TemplateRef_40_5:any;
  _NgIf_40_6:import19.Wrapper_NgIf;
  _text_41:any;
  _anchor_42:any;
  /*private*/ _vc_42:import11.ViewContainer;
  _TemplateRef_42_5:any;
  _NgIf_42_6:import19.Wrapper_NgIf;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _anchor_57:any;
  /*private*/ _vc_57:import11.ViewContainer;
  _TemplateRef_57_5:any;
  _NgIf_57_6:import19.Wrapper_NgIf;
  _text_58:any;
  _anchor_59:any;
  /*private*/ _vc_59:import11.ViewContainer;
  _TemplateRef_59_5:any;
  _NgIf_59_6:import19.Wrapper_NgIf;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _anchor_74:any;
  /*private*/ _vc_74:import11.ViewContainer;
  _TemplateRef_74_5:any;
  _NgIf_74_6:import19.Wrapper_NgIf;
  _text_75:any;
  _anchor_76:any;
  /*private*/ _vc_76:import11.ViewContainer;
  _TemplateRef_76_5:any;
  _NgIf_76_6:import19.Wrapper_NgIf;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _el_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _anchor_91:any;
  /*private*/ _vc_91:import11.ViewContainer;
  _TemplateRef_91_5:any;
  _NgIf_91_6:import19.Wrapper_NgIf;
  _text_92:any;
  _anchor_93:any;
  /*private*/ _vc_93:import11.ViewContainer;
  _TemplateRef_93_5:any;
  _NgIf_93_6:import19.Wrapper_NgIf;
  _text_94:any;
  _text_95:any;
  _text_96:any;
  _text_97:any;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _text_102:any;
  /*private*/ _expr_128:any;
  /*private*/ _expr_129:any;
  /*private*/ _expr_130:any;
  /*private*/ _expr_131:any;
  /*private*/ _expr_132:any;
  /*private*/ _expr_133:any;
  /*private*/ _expr_134:any;
  /*private*/ _expr_135:any;
  /*private*/ _expr_136:any;
  /*private*/ _expr_137:any;
  /*private*/ _expr_138:any;
  /*private*/ _expr_139:any;
  /*private*/ _expr_140:any;
  /*private*/ _expr_141:any;
  _pipe_gridActionsPipe_0:import20.GridActionsPipe;
  /*private*/ _expr_143:any;
  /*private*/ _expr_144:any;
  /*private*/ _expr_145:any;
  /*private*/ _expr_146:any;
  /*private*/ _expr_147:any;
  /*private*/ _expr_148:any;
  /*private*/ _expr_149:any;
  /*private*/ _expr_150:any;
  /*private*/ _expr_151:any;
  /*private*/ _expr_152:any;
  /*private*/ _expr_153:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TestcaseDetailsComponent0,renderType_TestcaseDetailsComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_128 = import1.UNINITIALIZED;
    this._expr_129 = import1.UNINITIALIZED;
    this._expr_130 = import1.UNINITIALIZED;
    this._expr_131 = import1.UNINITIALIZED;
    this._expr_132 = import1.UNINITIALIZED;
    this._expr_133 = import1.UNINITIALIZED;
    this._expr_134 = import1.UNINITIALIZED;
    this._expr_135 = import1.UNINITIALIZED;
    this._expr_136 = import1.UNINITIALIZED;
    this._expr_137 = import1.UNINITIALIZED;
    this._expr_138 = import1.UNINITIALIZED;
    this._expr_139 = import1.UNINITIALIZED;
    this._expr_140 = import1.UNINITIALIZED;
    this._expr_141 = import1.UNINITIALIZED;
    this._expr_143 = import1.UNINITIALIZED;
    this._expr_144 = import1.UNINITIALIZED;
    this._expr_145 = import1.UNINITIALIZED;
    this._expr_146 = import1.UNINITIALIZED;
    this._expr_147 = import1.UNINITIALIZED;
    this._expr_148 = import1.UNINITIALIZED;
    this._expr_149 = import1.UNINITIALIZED;
    this._expr_150 = import1.UNINITIALIZED;
    this._expr_151 = import1.UNINITIALIZED;
    this._expr_152 = import1.UNINITIALIZED;
    this._expr_153 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'zee-expander',new import3.InlineArray2(2,'id','zee-testcase-details-module'),(null as any));
    this._ExpanderDirective_2_3 = new import18.Wrapper_ExpanderDirective(new import17.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'id','zee-testcase-details-module-heading'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'h5',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Details',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n         ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n         ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n             ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'ul',new import3.InlineArray2(2,'class','zee-details-two-column-list'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_18,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'ID',(null as any));
    this._text_21 = this.renderer.createText(this._el_16,'\n                        ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_16,'span',new import3.InlineArray2(2,'id','type-val'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n                            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n                        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_16,'\n                    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._text_29 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_12,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n                    ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n                        ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_34,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Priority',(null as any));
    this._text_37 = this.renderer.createText(this._el_32,'\n                        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_32,'span',new import3.InlineArray2(2,'id','type-val'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n                            ',(null as any));
    this._anchor_40 = this.renderer.createTemplateAnchor(this._el_38,(null as any));
    this._vc_40 = new import11.ViewContainer(40,38,this,this._anchor_40);
    this._TemplateRef_40_5 = new import21.TemplateRef_(this,40,this._anchor_40);
    this._NgIf_40_6 = new import19.Wrapper_NgIf(this._vc_40.vcRef,this._TemplateRef_40_5);
    this._text_41 = this.renderer.createText(this._el_38,'\n                            ',(null as any));
    this._anchor_42 = this.renderer.createTemplateAnchor(this._el_38,(null as any));
    this._vc_42 = new import11.ViewContainer(42,38,this,this._anchor_42);
    this._TemplateRef_42_5 = new import21.TemplateRef_(this,42,this._anchor_42);
    this._NgIf_42_6 = new import19.Wrapper_NgIf(this._vc_42.vcRef,this._TemplateRef_42_5);
    this._text_43 = this.renderer.createText(this._el_38,'\n                        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_32,'\n                    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._text_46 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_12,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n                        ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_49,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_51,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Alt ID',(null as any));
    this._text_54 = this.renderer.createText(this._el_49,'\n                        ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_49,'span',new import3.InlineArray2(2,'id','type-val'),(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'\n                            ',(null as any));
    this._anchor_57 = this.renderer.createTemplateAnchor(this._el_55,(null as any));
    this._vc_57 = new import11.ViewContainer(57,55,this,this._anchor_57);
    this._TemplateRef_57_5 = new import21.TemplateRef_(this,57,this._anchor_57);
    this._NgIf_57_6 = new import19.Wrapper_NgIf(this._vc_57.vcRef,this._TemplateRef_57_5);
    this._text_58 = this.renderer.createText(this._el_55,'\n                            ',(null as any));
    this._anchor_59 = this.renderer.createTemplateAnchor(this._el_55,(null as any));
    this._vc_59 = new import11.ViewContainer(59,55,this,this._anchor_59);
    this._TemplateRef_59_5 = new import21.TemplateRef_(this,59,this._anchor_59);
    this._NgIf_59_6 = new import19.Wrapper_NgIf(this._vc_59.vcRef,this._TemplateRef_59_5);
    this._text_60 = this.renderer.createText(this._el_55,'\n                        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_49,'\n                     ',(null as any));
    this._text_62 = this.renderer.createText(this._el_47,'\n                ',(null as any));
    this._text_63 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_12,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'\n                    ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_64,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'\n                        ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_66,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_68,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'Tags',(null as any));
    this._text_71 = this.renderer.createText(this._el_66,'\n                        ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_66,'span',new import3.InlineArray2(2,'id','type-val'),(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n                            ',(null as any));
    this._anchor_74 = this.renderer.createTemplateAnchor(this._el_72,(null as any));
    this._vc_74 = new import11.ViewContainer(74,72,this,this._anchor_74);
    this._TemplateRef_74_5 = new import21.TemplateRef_(this,74,this._anchor_74);
    this._NgIf_74_6 = new import19.Wrapper_NgIf(this._vc_74.vcRef,this._TemplateRef_74_5);
    this._text_75 = this.renderer.createText(this._el_72,'\n                            ',(null as any));
    this._anchor_76 = this.renderer.createTemplateAnchor(this._el_72,(null as any));
    this._vc_76 = new import11.ViewContainer(76,72,this,this._anchor_76);
    this._TemplateRef_76_5 = new import21.TemplateRef_(this,76,this._anchor_76);
    this._NgIf_76_6 = new import19.Wrapper_NgIf(this._vc_76.vcRef,this._TemplateRef_76_5);
    this._text_77 = this.renderer.createText(this._el_72,'\n                        ',(null as any));
    this._text_78 = this.renderer.createText(this._el_66,'\n                     ',(null as any));
    this._text_79 = this.renderer.createText(this._el_64,'\n                ',(null as any));
    this._text_80 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_12,'li',new import3.InlineArray2(2,'style','width: 100%'),(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'\n                    ',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_81,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'\n                        ',(null as any));
    this._el_85 = import3.createRenderElement(this.renderer,this._el_83,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_85,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'Comment',(null as any));
    this._text_88 = this.renderer.createText(this._el_83,'\n                        ',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_83,'span',new import3.InlineArray2(2,'class','comment-inline-edit'),(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'\n                            ',(null as any));
    this._anchor_91 = this.renderer.createTemplateAnchor(this._el_89,(null as any));
    this._vc_91 = new import11.ViewContainer(91,89,this,this._anchor_91);
    this._TemplateRef_91_5 = new import21.TemplateRef_(this,91,this._anchor_91);
    this._NgIf_91_6 = new import19.Wrapper_NgIf(this._vc_91.vcRef,this._TemplateRef_91_5);
    this._text_92 = this.renderer.createText(this._el_89,'\n                            ',(null as any));
    this._anchor_93 = this.renderer.createTemplateAnchor(this._el_89,(null as any));
    this._vc_93 = new import11.ViewContainer(93,89,this,this._anchor_93);
    this._TemplateRef_93_5 = new import21.TemplateRef_(this,93,this._anchor_93);
    this._NgIf_93_6 = new import19.Wrapper_NgIf(this._vc_93.vcRef,this._TemplateRef_93_5);
    this._text_94 = this.renderer.createText(this._el_89,'\n                        ',(null as any));
    this._text_95 = this.renderer.createText(this._el_83,'\n                    ',(null as any));
    this._text_96 = this.renderer.createText(this._el_81,'\n                ',(null as any));
    this._text_97 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_98 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._text_99 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_100 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_101 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_102 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._pipe_gridActionsPipe_0 = new import20.GridActionsPipe(this.parentView.injectorGet(import10.DomSanitizer,this.parentIndex));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._anchor_40,
      this._text_41,
      this._anchor_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._anchor_57,
      this._text_58,
      this._anchor_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._anchor_74,
      this._text_75,
      this._anchor_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._el_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._anchor_91,
      this._text_92,
      this._anchor_93,
      this._text_94,
      this._text_95,
      this._text_96,
      this._text_97,
      this._text_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._text_102
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.TemplateRef) && (40 === requestNodeIndex))) { return this._TemplateRef_40_5; }
    if (((token === import22.NgIf) && (40 === requestNodeIndex))) { return this._NgIf_40_6.context; }
    if (((token === import21.TemplateRef) && (42 === requestNodeIndex))) { return this._TemplateRef_42_5; }
    if (((token === import22.NgIf) && (42 === requestNodeIndex))) { return this._NgIf_42_6.context; }
    if (((token === import21.TemplateRef) && (57 === requestNodeIndex))) { return this._TemplateRef_57_5; }
    if (((token === import22.NgIf) && (57 === requestNodeIndex))) { return this._NgIf_57_6.context; }
    if (((token === import21.TemplateRef) && (59 === requestNodeIndex))) { return this._TemplateRef_59_5; }
    if (((token === import22.NgIf) && (59 === requestNodeIndex))) { return this._NgIf_59_6.context; }
    if (((token === import21.TemplateRef) && (74 === requestNodeIndex))) { return this._TemplateRef_74_5; }
    if (((token === import22.NgIf) && (74 === requestNodeIndex))) { return this._NgIf_74_6.context; }
    if (((token === import21.TemplateRef) && (76 === requestNodeIndex))) { return this._TemplateRef_76_5; }
    if (((token === import22.NgIf) && (76 === requestNodeIndex))) { return this._NgIf_76_6.context; }
    if (((token === import21.TemplateRef) && (91 === requestNodeIndex))) { return this._TemplateRef_91_5; }
    if (((token === import22.NgIf) && (91 === requestNodeIndex))) { return this._NgIf_91_6.context; }
    if (((token === import21.TemplateRef) && (93 === requestNodeIndex))) { return this._TemplateRef_93_5; }
    if (((token === import22.NgIf) && (93 === requestNodeIndex))) { return this._NgIf_93_6.context; }
    if (((token === import23.ExpanderDirective) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._ExpanderDirective_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.action;
    this._ExpanderDirective_2_3.check_action(currVal_2_0_0,throwOnChange,false);
    this._ExpanderDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_40_0_0:boolean = !this.context.editable;
    this._NgIf_40_6.check_ngIf(currVal_40_0_0,throwOnChange,false);
    this._NgIf_40_6.ngDoCheck(this,this._anchor_40,throwOnChange);
    const currVal_42_0_0:any = this.context.editable;
    this._NgIf_42_6.check_ngIf(currVal_42_0_0,throwOnChange,false);
    this._NgIf_42_6.ngDoCheck(this,this._anchor_42,throwOnChange);
    const currVal_57_0_0:boolean = !this.context.editable;
    this._NgIf_57_6.check_ngIf(currVal_57_0_0,throwOnChange,false);
    this._NgIf_57_6.ngDoCheck(this,this._anchor_57,throwOnChange);
    const currVal_59_0_0:any = this.context.editable;
    this._NgIf_59_6.check_ngIf(currVal_59_0_0,throwOnChange,false);
    this._NgIf_59_6.ngDoCheck(this,this._anchor_59,throwOnChange);
    const currVal_74_0_0:boolean = !this.context.editable;
    this._NgIf_74_6.check_ngIf(currVal_74_0_0,throwOnChange,false);
    this._NgIf_74_6.ngDoCheck(this,this._anchor_74,throwOnChange);
    const currVal_76_0_0:any = this.context.editable;
    this._NgIf_76_6.check_ngIf(currVal_76_0_0,throwOnChange,false);
    this._NgIf_76_6.ngDoCheck(this,this._anchor_76,throwOnChange);
    const currVal_91_0_0:boolean = !this.context.editable;
    this._NgIf_91_6.check_ngIf(currVal_91_0_0,throwOnChange,false);
    this._NgIf_91_6.ngDoCheck(this,this._anchor_91,throwOnChange);
    const currVal_93_0_0:any = this.context.editable;
    this._NgIf_93_6.check_ngIf(currVal_93_0_0,throwOnChange,false);
    this._NgIf_93_6.ngDoCheck(this,this._anchor_93,throwOnChange);
    this._vc_40.detectChangesInNestedViews(throwOnChange);
    this._vc_42.detectChangesInNestedViews(throwOnChange);
    this._vc_57.detectChangesInNestedViews(throwOnChange);
    this._vc_59.detectChangesInNestedViews(throwOnChange);
    this._vc_74.detectChangesInNestedViews(throwOnChange);
    this._vc_76.detectChangesInNestedViews(throwOnChange);
    this._vc_91.detectChangesInNestedViews(throwOnChange);
    this._vc_93.detectChangesInNestedViews(throwOnChange);
    const currVal_128:any = 'zee-testcase-details-wrapper';
    if (import3.checkBinding(throwOnChange,this._expr_128,currVal_128)) {
      this.renderer.setElementProperty(this._el_0,'className',currVal_128);
      this._expr_128 = currVal_128;
    }
    const currVal_129:any = 'zee-module zee-module-toggle-wrapper';
    if (import3.checkBinding(throwOnChange,this._expr_129,currVal_129)) {
      this.renderer.setElementProperty(this._el_2,'className',currVal_129);
      this._expr_129 = currVal_129;
    }
    const currVal_130:any = 'zee-module-header';
    if (import3.checkBinding(throwOnChange,this._expr_130,currVal_130)) {
      this.renderer.setElementProperty(this._el_4,'className',currVal_130);
      this._expr_130 = currVal_130;
    }
    const currVal_131:any = 'zee-module-title';
    if (import3.checkBinding(throwOnChange,this._expr_131,currVal_131)) {
      this.renderer.setElementProperty(this._el_6,'className',currVal_131);
      this._expr_131 = currVal_131;
    }
    const currVal_132:any = 'zee-module-content zee-module-content-inline';
    if (import3.checkBinding(throwOnChange,this._expr_132,currVal_132)) {
      this.renderer.setElementProperty(this._el_10,'className',currVal_132);
      this._expr_132 = currVal_132;
    }
    const currVal_133:any = 'zee-column';
    if (import3.checkBinding(throwOnChange,this._expr_133,currVal_133)) {
      this.renderer.setElementProperty(this._el_14,'className',currVal_133);
      this._expr_133 = currVal_133;
    }
    const currVal_134:any = 'zee-column-wrap';
    if (import3.checkBinding(throwOnChange,this._expr_134,currVal_134)) {
      this.renderer.setElementProperty(this._el_16,'className',currVal_134);
      this._expr_134 = currVal_134;
    }
    const currVal_135:any = 'zee-column-name';
    if (import3.checkBinding(throwOnChange,this._expr_135,currVal_135)) {
      this.renderer.setElementProperty(this._el_18,'className',currVal_135);
      this._expr_135 = currVal_135;
    }
    const currVal_136:any = 'zee-column-value';
    if (import3.checkBinding(throwOnChange,this._expr_136,currVal_136)) {
      this.renderer.setElementProperty(this._el_22,'className',currVal_136);
      this._expr_136 = currVal_136;
    }
    const currVal_137:any = import3.inlineInterpolate(1,'',this.context.testcase.id,'');
    if (import3.checkBinding(throwOnChange,this._expr_137,currVal_137)) {
      this.renderer.setText(this._text_25,currVal_137);
      this._expr_137 = currVal_137;
    }
    const currVal_138:any = 'zee-column';
    if (import3.checkBinding(throwOnChange,this._expr_138,currVal_138)) {
      this.renderer.setElementProperty(this._el_30,'className',currVal_138);
      this._expr_138 = currVal_138;
    }
    const currVal_139:any = 'zee-column-wrap';
    if (import3.checkBinding(throwOnChange,this._expr_139,currVal_139)) {
      this.renderer.setElementProperty(this._el_32,'className',currVal_139);
      this._expr_139 = currVal_139;
    }
    const currVal_140:any = 'zee-column-name';
    if (import3.checkBinding(throwOnChange,this._expr_140,currVal_140)) {
      this.renderer.setElementProperty(this._el_34,'className',currVal_140);
      this._expr_140 = currVal_140;
    }
    const currVal_141:any = 'zee-column-value';
    if (import3.checkBinding(throwOnChange,this._expr_141,currVal_141)) {
      this.renderer.setElementProperty(this._el_38,'className',currVal_141);
      this._expr_141 = currVal_141;
    }
    const currVal_143:any = 'zee-column';
    if (import3.checkBinding(throwOnChange,this._expr_143,currVal_143)) {
      this.renderer.setElementProperty(this._el_47,'className',currVal_143);
      this._expr_143 = currVal_143;
    }
    const currVal_144:any = 'zee-column-wrap';
    if (import3.checkBinding(throwOnChange,this._expr_144,currVal_144)) {
      this.renderer.setElementProperty(this._el_49,'className',currVal_144);
      this._expr_144 = currVal_144;
    }
    const currVal_145:any = 'zee-column-name';
    if (import3.checkBinding(throwOnChange,this._expr_145,currVal_145)) {
      this.renderer.setElementProperty(this._el_51,'className',currVal_145);
      this._expr_145 = currVal_145;
    }
    const currVal_146:any = 'zee-column-value';
    if (import3.checkBinding(throwOnChange,this._expr_146,currVal_146)) {
      this.renderer.setElementProperty(this._el_55,'className',currVal_146);
      this._expr_146 = currVal_146;
    }
    const currVal_147:any = 'zee-column';
    if (import3.checkBinding(throwOnChange,this._expr_147,currVal_147)) {
      this.renderer.setElementProperty(this._el_64,'className',currVal_147);
      this._expr_147 = currVal_147;
    }
    const currVal_148:any = 'zee-column-wrap';
    if (import3.checkBinding(throwOnChange,this._expr_148,currVal_148)) {
      this.renderer.setElementProperty(this._el_66,'className',currVal_148);
      this._expr_148 = currVal_148;
    }
    const currVal_149:any = 'zee-column-name';
    if (import3.checkBinding(throwOnChange,this._expr_149,currVal_149)) {
      this.renderer.setElementProperty(this._el_68,'className',currVal_149);
      this._expr_149 = currVal_149;
    }
    const currVal_150:any = 'zee-column-value';
    if (import3.checkBinding(throwOnChange,this._expr_150,currVal_150)) {
      this.renderer.setElementProperty(this._el_72,'className',currVal_150);
      this._expr_150 = currVal_150;
    }
    const currVal_151:any = 'zee-column comment-wrapper';
    if (import3.checkBinding(throwOnChange,this._expr_151,currVal_151)) {
      this.renderer.setElementProperty(this._el_81,'className',currVal_151);
      this._expr_151 = currVal_151;
    }
    const currVal_152:any = 'zee-column-wrap textarea';
    if (import3.checkBinding(throwOnChange,this._expr_152,currVal_152)) {
      this.renderer.setElementProperty(this._el_83,'className',currVal_152);
      this._expr_152 = currVal_152;
    }
    const currVal_153:any = 'zee-column-name';
    if (import3.checkBinding(throwOnChange,this._expr_153,currVal_153)) {
      this.renderer.setElementProperty(this._el_85,'className',currVal_153);
      this._expr_153 = currVal_153;
    }
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._ExpanderDirective_2_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._vc_40.destroyNestedViews();
    this._vc_42.destroyNestedViews();
    this._vc_57.destroyNestedViews();
    this._vc_59.destroyNestedViews();
    this._vc_74.destroyNestedViews();
    this._vc_76.destroyNestedViews();
    this._vc_91.destroyNestedViews();
    this._vc_93.destroyNestedViews();
    this._ExpanderDirective_2_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 40)) { return new View_TestcaseDetailsComponent1(this.viewUtils,this,40,this._anchor_40,this._vc_40); }
    if ((nodeIndex == 42)) { return new View_TestcaseDetailsComponent2(this.viewUtils,this,42,this._anchor_42,this._vc_42); }
    if ((nodeIndex == 57)) { return new View_TestcaseDetailsComponent3(this.viewUtils,this,57,this._anchor_57,this._vc_57); }
    if ((nodeIndex == 59)) { return new View_TestcaseDetailsComponent4(this.viewUtils,this,59,this._anchor_59,this._vc_59); }
    if ((nodeIndex == 74)) { return new View_TestcaseDetailsComponent5(this.viewUtils,this,74,this._anchor_74,this._vc_74); }
    if ((nodeIndex == 76)) { return new View_TestcaseDetailsComponent6(this.viewUtils,this,76,this._anchor_76,this._vc_76); }
    if ((nodeIndex == 91)) { return new View_TestcaseDetailsComponent7(this.viewUtils,this,91,this._anchor_91,this._vc_91); }
    if ((nodeIndex == 93)) { return new View_TestcaseDetailsComponent8(this.viewUtils,this,93,this._anchor_93,this._vc_93); }
    return (null as any);
  }
}