/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../app/view/components/common/customfield/select_field.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../../../../app/view/components/inline_edit/inline_edit.component';
import * as import10 from '../../../../../../app/utils/scripts/utils';
import * as import11 from '../../inline_edit/inline_edit.component.ngfactory';
import * as import12 from '@angular/forms/src/form_builder';
import * as import13 from '@angular/core/src/linker/element_ref';
export class Wrapper_SelectFieldComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SelectFieldComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  subscription0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.SelectFieldComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_field(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.field = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.onSaveField.subscribe(_eventHandler.bind(view,'onSaveField'))); }
  }
}
var renderType_SelectFieldComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_SelectFieldComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.SelectFieldComponent>;
  _SelectFieldComponent_0_3:Wrapper_SelectFieldComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SelectFieldComponent_Host0,renderType_SelectFieldComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'field-select',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_SelectFieldComponent0(this.viewUtils,this,0,this._el_0);
    this._SelectFieldComponent_0_3 = new Wrapper_SelectFieldComponent();
    this.compView_0.create(this._SelectFieldComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._SelectFieldComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SelectFieldComponent) && (0 === requestNodeIndex))) { return this._SelectFieldComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SelectFieldComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._SelectFieldComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SelectFieldComponentNgFactory:import8.ComponentFactory<import0.SelectFieldComponent> = new import8.ComponentFactory<import0.SelectFieldComponent>('field-select',View_SelectFieldComponent_Host0,import0.SelectFieldComponent);
const styles_SelectFieldComponent:any[] = ([] as any[]);
var renderType_SelectFieldComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_SelectFieldComponent,{});
export class View_SelectFieldComponent0 extends import2.AppView<import0.SelectFieldComponent> {
  _text_0:any;
  _el_1:any;
  compView_1:import2.AppView<import9.InlineEditComponent>;
  _UtililtyFunctions_1_3:import10.UtililtyFunctions;
  _InlineEditComponent_1_4:import11.Wrapper_InlineEditComponent;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SelectFieldComponent0,renderType_SelectFieldComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'zephyr-inline-edit',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_1 = new import11.View_InlineEditComponent0(this.viewUtils,this,1,this._el_1);
    this._UtililtyFunctions_1_3 = new import10.UtililtyFunctions();
    this._InlineEditComponent_1_4 = new import11.Wrapper_InlineEditComponent(this.parentView.injectorGet(import12.FormBuilder,this.parentIndex),new import13.ElementRef(this._el_1),this.compView_1.ref,this._UtililtyFunctions_1_3);
    this.compView_1.create(this._InlineEditComponent_1_4.context);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'onSubmit',(null as any)),this.eventHandler(this.handleEvent_1));
    this._InlineEditComponent_1_4.subscribe(this,this.eventHandler(this.handleEvent_1),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.UtililtyFunctions) && (1 === requestNodeIndex))) { return this._UtililtyFunctions_1_3; }
    if (((token === import9.InlineEditComponent) && (1 === requestNodeIndex))) { return this._InlineEditComponent_1_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this.context.field.value;
    this._InlineEditComponent_1_4.check_field(currVal_1_0_0,throwOnChange,false);
    const currVal_1_0_1:any = 'singleselect';
    this._InlineEditComponent_1_4.check_editType(currVal_1_0_1,throwOnChange,false);
    const currVal_1_0_2:any = this.context.field.fieldValues;
    this._InlineEditComponent_1_4.check_fieldOptions(currVal_1_0_2,throwOnChange,false);
    const currVal_1_0_3:any = this.context.getSelectedValue(this.context.field.value);
    this._InlineEditComponent_1_4.check_selectedOption(currVal_1_0_3,throwOnChange,false);
    const currVal_1_0_4:any = 'None';
    this._InlineEditComponent_1_4.check_placeholder(currVal_1_0_4,throwOnChange,false);
    const currVal_1_0_5:any = this.context.getSelect2Options();
    this._InlineEditComponent_1_4.check_editOptions(currVal_1_0_5,throwOnChange,false);
    if (this._InlineEditComponent_1_4.ngDoCheck(this,this._el_1,throwOnChange)) { this.compView_1.markAsCheckOnce(); }
    this.compView_1.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._InlineEditComponent_1_4.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this.compView_1.destroy();
    this._InlineEditComponent_1_4.ngOnDestroy();
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSubmit')) {
      const pd_sub_0:any = ((<any>this.context.saveCustomfield($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}